Survey options updated
redhat-cop/automate_tower_genie_collections pull request #133
Opened 2021-01-15 05:15 UTC by sean-m-sullivan

### What does this PR do?
Updated survey options, also ran into problem with the openshift cluster, and changing username for now.

2021-01-15 16:56 UTC, Tompage1994 requested changes
Looks good. Just a couple of small things

2021-01-15 16:56 UTC, Tompage1994 commented on .github/tower_install_inventories/openshift_awx
> +openshift_user=kubeadmin
Could you add this to the changelog. I'm not 100% sure I agree we should change to kubeadmin as that probably isn't good practice. I guess there isnt necessarily a sensible and usable default (maybe we could pick it up from the kubeconfig or something?) Though if you update the changelog for now we can think about that in the future.

2021-01-15 16:56 UTC, Tompage1994 commented on roles/job_templates/README.md
> +|`survey_spec`|""|no|dict|JSON/YAML dict formatted survey definition. Alais of survey_spec|
I assume this should be
`|`survey`|""|no|dict|JSON/YAML dict formatted survey definition. Alias of survey_spec|`

2021-01-15 18:07 UTC, sean-m-sullivan commented on .github/tower_install_inventories/openshift_awx
> +openshift_user=kubeadmin
Even better I found how to grant the user the right privileges so we can use developer and not make this change.

2021-01-18 08:23 UTC, Tompage1994 requested changes
Just the one README correction then I'm happy

2021-01-18 08:23 UTC, Tompage1994 commented on roles/job_templates/README.md
> +|`survey_spec`|""|no|dict|JSON/YAML dict formatted survey definition. Alias of survey_spec|
I think this should be `survey` rather than `survey_spec` shouldn't it?

2021-01-18 14:46 UTC, sean-m-sullivan commented on roles/job_templates/README.md
> +|`survey_spec`|""|no|dict|JSON/YAML dict formatted survey definition. Alias of survey_spec|
One of them should, fixing.

2021-01-18 14:51 UTC, Tompage1994 approved these changes
LGTM

2021-01-18 14:53 UTC, merged