Add launch, update and cancel roles
redhat-cop/automate_tower_genie_collections pull request #138
Opened 2021-01-27 16:38 UTC by sean-m-sullivan

### What does this PR do?
Adds launch, update, and cancel roles to be in line with available tower modules.

### How should this be tested?
Automated tests are updated to use the new roles. Also the Automated tests are updated to work with changes in awx.

### Is there a relevant Issue open for this?
#131

2021-01-28 09:21 UTC, Tompage1994 requested changes
Good work. A fair few things to correct, though most are just repeats throughout

2021-01-28 09:21 UTC, Tompage1994 commented on roles/ad_hoc_command/README.md
> +|`tower_configuration_ad_hoc_command_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
This line should be describing `tower_ad_hoc_commands`

2021-01-28 09:21 UTC, Tompage1994 commented on roles/ad_hoc_command/README.md
> +[************](************)
Could you fill this in please

2021-01-28 09:21 UTC, Tompage1994 commented on roles/ad_hoc_command_cancel/README.md
> +|`tower_configuration_ad_hoc_command_cancel_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
this should be for `tower_ad_hoc_commands_cancel `

2021-01-28 09:21 UTC, Tompage1994 commented on roles/ad_hoc_command_cancel/README.md
> +[************](************)
Can you fill this in please

2021-01-28 09:21 UTC, Tompage1994 commented on roles/ad_hoc_command_cancel/tests/collections/requirements.yml
> +    version: 11.2.0
Should this really be defined here? Not sure whether we do in other places and will make it harder to maintain going forwards

2021-01-28 09:21 UTC, Tompage1994 commented on roles/inventory_source_update/README.md
> +|`tower_configuration_inventory_source_update_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Should be for `tower_inventory_sources`

2021-01-28 09:21 UTC, Tompage1994 commented on roles/inventory_source_update/README.md
> +[************](************)
Fill in please

2021-01-28 09:21 UTC, Tompage1994 commented on roles/job_launch/README.md
> +|`tower_configuration_job_launch_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Should be `tower_launch_jobs`

2021-01-28 09:21 UTC, Tompage1994 commented on roles/job_launch/README.md
> +The role defaults to False as normally the add ******* task does not include sensitive information.
Can you fill in these to be relevant to the role

2021-01-28 09:21 UTC, Tompage1994 commented on roles/job_launch/README.md
> +[************](************)
And fill in this again

2021-01-28 09:21 UTC, Tompage1994 commented on roles/jobs_cancel/README.md
> +|`tower_configuration_jobs_cancel_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Same issue. Again should be for `tower_cancel_jobs`

2021-01-28 09:21 UTC, Tompage1994 commented on roles/jobs_cancel/README.md
> +tower_configuration_*******_secure_logging defaults to the value of tower_configuration_secure_logging if it is not explicitly called. This allows for secure logging to be toggled for the entire suit
Fill in

2021-01-28 09:21 UTC, Tompage1994 commented on roles/jobs_cancel/README.md
> +[************](************)
Fill in

2021-01-28 09:21 UTC, Tompage1994 commented on roles/jobs_cancel/tasks/main.yml
> +    job_id:                   "{{ __jobs_cancel_item.id }}"
I assume this is wrong

2021-01-28 09:21 UTC, Tompage1994 commented on roles/jobs_cancel/tasks/main.yml
> +    job_id:                   "{{ __jobs_cancel_item.id }}"
Actually its not. I've only just spotted these. Are we doing this in any other roles? A quick look at a couple says we are not, so perhaps we shouldnt be straying from our standard?

2021-01-28 09:21 UTC, Tompage1994 commented on roles/project_update/README.md
> +tower_projects:
These items are wrong

2021-01-28 09:21 UTC, Tompage1994 commented on roles/project_update/README.md
> +tower_projects:
Unless we are forcing an update using this? Not sure we necessarily want to use the tower_project item for this. Unless we specify an option such as `update: true`

2021-01-28 09:21 UTC, Tompage1994 commented on roles/project_update/README.md
> +[************](************)
Fill in

2021-01-28 09:21 UTC, Tompage1994 commented on roles/project_update/README.md
> +|`tower_configuration_project_update_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Should be for `tower_projects`

2021-01-28 09:21 UTC, Tompage1994 commented on roles/project_update/README.md
> +The role defaults to False as normally the add ******* task does not include sensitive information.
Fill these please

2021-01-28 09:21 UTC, Tompage1994 commented on roles/workflow_launch/README.md
> +|`tower_configuration_workflow_launch_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Shoudl be for tower_workflow_launch_jobs

2021-01-28 09:21 UTC, Tompage1994 commented on roles/workflow_launch/README.md
> +tower_configuration_*******_secure_logging defaults to the value of tower_configuration_secure_logging if it is not explicitly called. This allows for secure logging to be toggled for the entire suit
Fill these

2021-01-28 09:21 UTC, Tompage1994 commented on roles/workflow_launch/README.md
> +[************](************)
And these

2021-01-28 13:46 UTC, sean-m-sullivan commented on roles/ad_hoc_command_cancel/tests/collections/requirements.yml
> +    version: 11.2.0
Updating all of them to remove the version, think the requirements file should be there, but agree on removing version to make it easier to maintain.

2021-01-28 13:51 UTC, sean-m-sullivan commented on roles/ad_hoc_command/README.md
> +|`tower_configuration_ad_hoc_command_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Fixed and updated.

2021-01-28 13:52 UTC, sean-m-sullivan commented on roles/ad_hoc_command/README.md
> +[************](************)
Fixed and updated.

2021-01-28 14:16 UTC, sean-m-sullivan commented on roles/jobs_cancel/tasks/main.yml
> +    job_id:                   "{{ __jobs_cancel_item.id }}"
I started doing it on new roles for any internal variables to match the oasis standard. The basics is, if the user will not be using the variable it should be started as __ to denote an internal variable. 

We can change it to the old standard, but was thinking we should change it over collection wide to the new.

2021-01-28 14:23 UTC, sean-m-sullivan commented on roles/workflow_launch/README.md
> +[************](************)
Updated and fixed

2021-01-28 14:23 UTC, sean-m-sullivan commented on roles/workflow_launch/README.md
> +tower_configuration_*******_secure_logging defaults to the value of tower_configuration_secure_logging if it is not explicitly called. This allows for secure logging to be toggled for the entire suit
Updated and fixed

2021-01-28 14:24 UTC, sean-m-sullivan commented on roles/project_update/README.md
> +[************](************)
Updated and fixed

2021-01-28 14:25 UTC, sean-m-sullivan commented on roles/project_update/README.md
> +tower_projects:
I actually made it so it used the tower projects variable by default so users can set which ones to be true or not in the same config file rather then keeping the data updated in two places. Or should we do it that way? They could always load a separate file with the same variable set.

2021-01-28 14:25 UTC, sean-m-sullivan commented on roles/project_update/README.md
> +The role defaults to False as normally the add ******* task does not include sensitive information.
Updated and fixed

2021-01-28 14:25 UTC, sean-m-sullivan commented on roles/project_update/README.md
> +|`tower_configuration_project_update_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Updated and fixed

2021-01-28 14:25 UTC, sean-m-sullivan commented on roles/jobs_cancel/README.md
> +[************](************)
Updated and fixed

2021-01-28 14:25 UTC, sean-m-sullivan commented on roles/jobs_cancel/README.md
> +tower_configuration_*******_secure_logging defaults to the value of tower_configuration_secure_logging if it is not explicitly called. This allows for secure logging to be toggled for the entire suit
Updated and fixed

2021-01-28 14:25 UTC, sean-m-sullivan commented on roles/jobs_cancel/README.md
> +|`tower_configuration_jobs_cancel_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Updated and fixed

2021-01-28 14:26 UTC, sean-m-sullivan commented on roles/job_launch/README.md
> +[************](************)
Updated and fixed

2021-01-28 14:26 UTC, sean-m-sullivan commented on roles/job_launch/README.md
> +The role defaults to False as normally the add ******* task does not include sensitive information.
Updated and fixed

2021-01-28 14:26 UTC, sean-m-sullivan commented on roles/job_launch/README.md
> +|`tower_configuration_job_launch_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Updated and fixed

2021-01-28 14:26 UTC, sean-m-sullivan commented on roles/inventory_source_update/README.md
> +[************](************)
Updated and fixed

2021-01-28 14:26 UTC, sean-m-sullivan commented on roles/inventory_source_update/README.md
> +|`tower_configuration_inventory_source_update_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Updated and fixed

2021-01-28 14:26 UTC, sean-m-sullivan commented on roles/ad_hoc_command_cancel/README.md
> +[************](************)
Updated and fixed

2021-01-28 14:26 UTC, sean-m-sullivan commented on roles/ad_hoc_command_cancel/README.md
> +|`tower_configuration_ad_hoc_command_cancel_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Updated and fixed

2021-01-28 14:27 UTC, sean-m-sullivan commented on roles/ad_hoc_command/README.md
> +[************](************)
Updated and fixed

2021-01-28 14:27 UTC, sean-m-sullivan commented on roles/ad_hoc_command/README.md
> +|`tower_configuration_ad_hoc_command_secure_logging`|`see below`|yes|Data structure describing your orgainzation or orgainzations Described below.||
Updated and fixed

2021-01-28 15:28 UTC, kedark3 commented on roles/jobs_cancel/tasks/main.yml
> +    job_id:                   "{{ __jobs_cancel_item.id }}"
i think its good way to indicate private vars.

2021-01-28 15:30 UTC, kedark3 approved these changes
Overall looks great at a quick glance. I will let Tom finalize it as its  big PR :)

2021-01-29 09:03 UTC, Tompage1994 commented on roles/jobs_cancel/tasks/main.yml
> +    job_id:                   "{{ __jobs_cancel_item.id }}"
Im happy with it, we should probably make sure we have one standard and go back and change any which don't match

2021-01-29 09:06 UTC, Tompage1994 commented on roles/project_update/README.md
> +tower_projects:
I think having just one copy of the list of projects is a good idea. But under this way we dont have any logic to say whether we actually want to update or not. Maybe an option of `update: true` would be a good idea and we can just do a `when: __project_update_update_item.update`

2021-01-29 09:09 UTC, Tompage1994 approved these changes
Looks good now!

Thanks for the HUGE load of fixes

2021-01-29 09:10 UTC, Tompage1994 requested changes
Actually, can you just add a changelog for this addition as it does add new functionality. Then happy to merge

2021-01-29 14:52 UTC, sean-m-sullivan commented on roles/jobs_cancel/tasks/main.yml
> +    job_id:                   "{{ __jobs_cancel_item.id }}"
I'm thinking the same Tom, We adopt more of the Oasis standards, and this one I like, and we'll make an issue and go back and change the others.

2021-01-29 15:08 UTC, sean-m-sullivan commented on roles/project_update/README.md
> +tower_projects:
Testing that now, think its a good solution

2021-01-29 16:06 UTC, sean-m-sullivan commented on roles/project_update/README.md
> +tower_projects:
Done and tested.

2021-02-01 20:47 UTC, merged