Update to remove awx.awx from module names
redhat-cop/automate_tower_genie_collections pull request #140
Opened 2021-02-08 21:55 UTC by sean-m-sullivan

### What does this PR do?
This PR updates the yaml and ansible lint to their latest versions, and by extension allows us to remove awx.awx from module names and still pass ansible lint. These are then tested against a deployment of awx, and have been tested on tower.

### Is there a relevant Issue open for this?
resolves #115

2021-02-10 14:47 UTC, Tompage1994 approved these changes
Just one question to check but otherwise happy 👍

2021-02-10 14:47 UTC, Tompage1994 commented on changelogs/fragments/ansible_lint.yml
> +  - Updated to allow use of either awx.awx or ansible.tower
Is it actually a breaking change? Will old playbooks fail? If so it may be worth having a major change log in the README so anybody who comes back to the collection is aware of what needs to be changed in their playbooks

2021-02-10 15:28 UTC, sean-m-sullivan commented on changelogs/fragments/ansible_lint.yml
> +  - Updated to allow use of either awx.awx or ansible.tower
Without the opening playbook listing awx.awx, its not going to find the right modules specifcally for applications and tower notification template. 

Did a deep dive and for those that were included in regular ansible 2.9, they map it to the new awx.awx modules, and those aren't mapped as they didn't come out till later.

2021-02-10 15:57 UTC, Tompage1994 commented on changelogs/fragments/ansible_lint.yml
> +  - Updated to allow use of either awx.awx or ansible.tower
ok, probably worth calling out in the README that the collection needs to be specified in the playbook?

2021-02-10 16:10 UTC, sean-m-sullivan commented on changelogs/fragments/ansible_lint.yml
> +  - Updated to allow use of either awx.awx or ansible.tower
Updated the base readme under using the collection, Should we update it elsewhere?

2021-02-11 01:27 UTC, sean-m-sullivan reviewed
Reviewed all the files again, fixed a few errors, I think its ready.

2021-02-11 02:02 UTC, sean-m-sullivan commented
After rereading yaml lint rules, and seeing as warnings were not showing up easily, I've updated the lint rules to fit our criteria, and also adjusted the colon rule and several spaces before colon areas we were missing.

2021-02-11 08:04 UTC, Tompage1994 requested changes
Just a single minor typo in the readme. Probably best to make sure the main readme is as good as possible. After fixing that Im completely happy for this to be merged

2021-02-11 08:04 UTC, Tompage1994 commented on README.md
> +Otherwise it will look for for the modules only in your base installation. If there are errors complaining about "counldn't resolve module/action' this is the most likely cause.
`Otherwise it will look for for the modules only in your base installation. If there are errors complaining about "couldn't resolve module/action" this is the most likely cause.`

2021-02-11 15:03 UTC, Tompage1994 requested changes

2021-02-11 15:03 UTC, Tompage1994 commented on README.md
> +Otherwise it will look for the modules only in your base installation. If there are errors complaining about "counldn't resolve module/action' this is the most likely cause.
That wasn't even the typo I spotted 😂

Could you replace `counldn't` with `couldn't` and then the final single quote should be a double quote

2021-02-11 15:08 UTC, sean-m-sullivan commented on README.md
> +Otherwise it will look for the modules only in your base installation. If there are errors complaining about "counldn't resolve module/action' this is the most likely cause.
Whoops on it.

2021-02-11 15:10 UTC, sean-m-sullivan commented on README.md
> +Otherwise it will look for for the modules only in your base installation. If there are errors complaining about "counldn't resolve module/action' this is the most likely cause.
Thought you were just highlighting missed what you pointed out later.

2021-02-11 15:28 UTC, Tompage1994 approved these changes
Looks good now

2021-02-11 15:28 UTC, merged