Use credential name.
redhat-cop/automate_tower_genie_collections pull request #145
Opened 2021-02-12 16:37 UTC by ghurel-rh

### What does this PR do?
Allows to directly use exported project YAML for import.

### How should this be tested?
Export an existing project from an existing Tower using `awx export --projects <PROJECT NAME>`.
Import the resulting YAML using the role projects from this collection.

### Is there a relevant Issue open for this?
resolves #144

2021-02-13 09:10 UTC, Tompage1994 requested changes
Hi, and thanks for the contribution.

Would you be able to add an example of `scm_credential` being used (from the export) in `playbooks/tower_configs_export_model/projects_export.yml`. This will then be used in the automated integration testing for this repo.

2021-02-15 12:29 UTC, ghurel-rh commented
Hi,
I'm not sure if the failed tests really come from my change. If so, could you please provide some guidelines/hints about how to fix them ? Thanks.

2021-02-15 12:39 UTC, ghurel-rh commented
Hi @Tompage1994 , just saw your request and pushed an example of a project exported with `awx export` command from awxkit 17.0.0.
As you see,  there is no a `scm_credential` field that is directly exported; instead this is a `credential` dict field, and the goal of this PR is to directly leverage the key `name` of that dict instead. Thanks !

2021-02-15 14:05 UTC, Tompage1994 commented
Apologies, I meant the `credential` field as you have filled in in the test. I can see the test is failing and that is because the credential you have specified does not exist. You should be able to change the name of the credential to `AWX-Collection-tests-tower_workflow_job_template-scm-cred` as that is created in the credentials section.

2021-02-15 15:00 UTC, ghurel-rh commented
My bad, I fixed it and the test seems now OK.

2021-02-15 15:15 UTC, Tompage1994 commented
Perfect. Thanks!

2021-02-15 15:15 UTC, Tompage1994 approved these changes

2021-02-15 15:15 UTC, merged

2021-02-15 15:29 UTC, ghurel-rh commented
Glad it has been so quick, thanks to you and the team.