Linguist fix
redhat-cop/automate_tower_genie_collections pull request #146
Opened 2021-02-12 22:12 UTC by djdanielsson

### What does this PR do?
forcing linguist to read yml/yaml files as a language so it stops calling the repo html

### How should this be tested?
Automated

### Is there a relevant Issue open for this?
no

### Other Relevant info, PRs, etc.
none

2021-02-12 22:22 UTC, djdanielsson commented
I don't understand how it failed the lint... the extra line is there you can see that in the 2nd commit...

2021-02-13 09:22 UTC, Tompage1994 requested changes
Thanks for the contribution

2021-02-13 09:22 UTC, Tompage1994 commented on .gitattributes
> +
This is one too many lines at the end. The github UI only seems to show one of them but I've checked out your code and can see you have blank line on lines 3 and 4. If you delete line 4 then it should all pass linting.

2021-02-13 14:36 UTC, sean-m-sullivan commented on .gitattributes
> +
Removed it, we will see how the testing goes :)

2021-02-13 14:55 UTC, sean-m-sullivan approved these changes
Looks good, That fixed it. Didn't even know about this.

2021-02-13 14:56 UTC, merged