Update Tower configuration to use new minikube based install for testing awx
redhat-cop/automate_tower_genie_collections pull request #174
Opened 2021-04-25 19:14 UTC by sean-m-sullivan

### What does this PR do?
Update Tower configuration to use new minikube based install for testing awx
Finally figured out what was wrong, and have even submitted a bug for the operator with decreasing postgres defaults. Have this working locally and on my actions, it takes a bit to run, but its working!

### How should this be tested?
The tests should hopefully work now

2021-04-25 19:15 UTC, sean-m-sullivan commented on playbooks/tower_configs/tower_credentials.yml
> -  - credential_type: Machine
Not sure why, but the modules were complaining that two existed when trying to do Job templates, The rest of the demo objects didn't create duplicates, but removed this one till its figured out.

2021-04-25 19:59 UTC, Tompage1994 requested changes
Generally looks good though looks like the checks are failing for a genuine cause. I guess that should be fixed by a separate PR?

2021-04-25 20:15 UTC, sean-m-sullivan commented
I am looking into it, and think I may have found a short term fix, and the problem itself should be solved overall by the Workflow Schema PR, once that is published soon, Its already in awx.awx devel.

2021-04-25 20:34 UTC, sean-m-sullivan commented
@Tompage1994 You may be right on rather then trying to fix all of our issues with this PR, and leaving it to a separate one. From what I am seeing its reliably getting us to awx now, including the many times I've run it leading to this. I'll revisit tomorrow, and we can discuss then if you want.

2021-04-26 23:32 UTC, sean-m-sullivan commented
Seems auth fails every so often on the settings, and the adhoc was unable to be canceled due to it being finished before I could cancel, so reduced the # of adhocs. But passing checks now. @Tompage1994

2021-04-27 08:20 UTC, Tompage1994 requested changes
Looks good to me.

Only change I would like to see is all the kubernetes definitions under a kube directory (e.g. `.github/workflow-config/kube/<file>`)

2021-04-27 08:20 UTC, Tompage1994 commented on playbooks/tower_configs/tower_credentials.yml
> -  - credential_type: Machine
I suspect its probably because when AWX is spun up it has the Demo Credential (and presumably the other 'demo' objects) there.

2021-04-27 12:41 UTC, sean-m-sullivan commented on playbooks/tower_configs/tower_credentials.yml
> -  - credential_type: Machine
It shouldn't but somehow its slightly different somehow, but I couldn't see it.

2021-05-04 12:41 UTC, Tompage1994 approved these changes

2021-05-04 12:41 UTC, merged