Removed update_secrets parameter from users role as it is no longer valid
redhat-cop/automate_tower_genie_collections pull request #184
Opened 2021-05-24 05:19 UTC by suppaduppax

### What does this PR do?
awx.tower_user  no longer contains the update_secrets parameter so the users role fails when run. This pull request removes that parameter from the task in the users role

2021-05-24 10:09 UTC, Tompage1994 requested changes
It looks as though `update_secrets` is an option which has been added recently rather than removed.

Having a look at latest awx.awx I can see the option is there https://docs.ansible.com/ansible/latest/collections/awx/awx/tower_user_module.html and the same in the codebase for `devel`. 

I think there is a valid issue here, however, and that is to default the option to omit rather than `false`.

2021-05-25 03:39 UTC, suppaduppax commented
Made the requested change

2021-05-25 05:21 UTC, suppaduppax commented
On a second look, should default be set to 'true' ? The role readme says the default is 'true', but the default value is currently 'false' in the main branch

2021-05-25 07:33 UTC, Tompage1994 commented
The default will be to omit. `default(omit, true)` doesn't do what you would think. The true is to ensure any false value causes the value to be omitted. In this case probably best to just use `default(omit)`. This will then mean if no value is given the awx collection (or the tower collection's) default value will be used. In this case the value is true. 

From awx collection:
```
update_secrets:
      description:
        - C(true) will always change password if user specifies password, even if API gives $encrypted$ for password.
        - C(false) will only set the password if other values change too.
      type: bool
      default: true
```

So I think the value we need here is `default(omit)`

Thanks!

2021-05-25 17:00 UTC, suppaduppax commented
Change made

2021-05-25 17:48 UTC, Tompage1994 approved these changes
Looks good!

2021-05-27 08:08 UTC, merged