Added variable to control if galaxy_credential should be added and added async task to manage organization object
redhat-cop/automate_tower_genie_collections pull request #269
Opened 2022-02-12 07:34 UTC by silvinux

### What does this PR do?
Added variable "assign_galaxy_organizations_to_org" to control if galaxy_credential should be omited when organization will be created. Galaxy credential must exists before try to  added as a organization credential.
 
Also an async task has been added to manage organization object when there are a bunch of objects to be added.

### How should this be tested?
Automated tests are preferred, but not always doable - especially for infrastructure. Include commands to run your new feature, and also post-run commands to validate that it worked. (please use code blocks to format code samples)

### Is there a relevant Issue open for this?
Provide a link to any open issues that describe the problem you are solving.
resolves #<number>

### Other Relevant info, PRs, etc.
Please provide link to other PRs that may be related (blocking, resolves, etc. etc.)

2022-02-12 15:24 UTC, sean-m-sullivan commented on roles/organizations/tasks/main.yml
> +    galaxy_organizations:                 "{{ (__controller_organizations_item.galaxy_organizations | default(omit)) if (assign_galaxy_organizations_to_org is defined and assign_galaxy_organizations_
This needs to stay as an option, its the relevant field from the module [here](https://github.com/ansible/awx/blob/b26c1c16b985d523c8aa4c35ec9e95bb4f679133/awx_collection/plugins/modules/organization.py#L83)
We can Add a field for the galaxy organization, but want to keep parity with the original module fields.

2022-02-12 15:24 UTC, sean-m-sullivan commented on roles/organizations/README.md
> +|`assign_galaxy_credentials_to_org`|""|no|Boolean to indicate weather credentials should be assigned or not. It should be noted that credentials must exist before add it. |
Typo, fix to whether

2022-02-12 15:26 UTC, sean-m-sullivan commented on roles/organizations/tasks/main.yml
> +  async: 1000
I wasn't aware a job was made to create an organization, this is interesting, and may be needed, but may have another solution.

2022-02-12 15:29 UTC, sean-m-sullivan commented on roles/projects/tasks/main.yml
> +- name: "Configure Controller Projects | Wait for finish the projects creation"
How does this work with the [project_item.wait,](https://github.com/ansible/awx/blob/b26c1c16b985d523c8aa4c35ec9e95bb4f679133/awx_collection/plugins/modules/project.py#L136) 
That should be set to wait for project to be completed, rather then using a seperate task. Might it be easier to set an option to default to always wait, similar to no log?
Like
```
wait: "{{ controller_wait_on_projects | default(__controller_project_item.wait | default(omit, true)) }}"
```

2022-02-12 15:30 UTC, sean-m-sullivan requested changes
Left feedback on three items to review/change before merge. 
This looks really good, and had not thought of the organization implications in the object diff and credentials!

2022-02-12 17:04 UTC, silvinux commented on roles/organizations/tasks/main.yml
> +    galaxy_organizations:                 "{{ (__controller_organizations_item.galaxy_organizations | default(omit)) if (assign_galaxy_organizations_to_org is defined and assign_galaxy_organizations_
I messed up changing it. I didn't mean to change the variable name.

2022-02-12 17:04 UTC, silvinux commented on roles/organizations/README.md
> +|`assign_galaxy_credentials_to_org`|""|no|Boolean to indicate weather credentials should be assigned or not. It should be noted that credentials must exist before add it. |
Fixed.

2022-02-12 17:07 UTC, silvinux commented on roles/organizations/tasks/main.yml
> +  async: 1000
We normally execute tasks as async to speed up things. when you have a lots objects to add, you can do it like this and will be quicker.

2022-02-12 17:08 UTC, silvinux commented on roles/projects/tasks/main.yml
> +- name: "Configure Controller Projects | Wait for finish the projects creation"
As I said before, is just to speed up the process. Then add a task to control the previous task. When you have a buch of objects to add is helpful.

2022-02-12 17:45 UTC, sean-m-sullivan commented on roles/projects/tasks/main.yml
> +- name: "Configure Controller Projects | Wait for finish the projects creation"
I think the job Id is what threw me off, thinking ti was waiting on a Tower job :), If this speeds things up, Especially workflows with their nodes!!, we should add it to more objects :)

2022-02-12 17:51 UTC, sean-m-sullivan commented on roles/organizations/tasks/main.yml
> +    galaxy_credentials:                 "{{ (__controller_organizations_item.galaxy_organizations | default(omit)) if (assign_galaxy_organizations_to_org is defined and assign_galaxy_organizations_to
Went and consulted your code in gitlab here It should be 
    galaxy_credentials: "{{ (__controller_organizations_item.galaxy_credentials | default(omit)) if (assign_galaxy_credentials_to_org is defined and assign_galaxy_credentials_to_org) else omit }}"
    
    The key __controller_organizations_item.galaxy_organizations needs to be changed to credentials

2022-02-12 18:00 UTC, sean-m-sullivan commented
Found one more thing, a changelog fragment file needs to be created in the 
https://github.com/redhat-cop/tower_configuration/tree/devel/changelogs/fragments

An example can be found in the[ legacy tower changes](https://github.com/redhat-cop/tower_configuration/blob/legacy_tower_v1/changelogs/fragments/playbooks.yml)

Reference here
https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst#changelog-fragment-categories

Particularly a breaking change like so
---
breaking_changes:
  - galaxy credentials in the organization role now require assign_galaxy_organizations_to_org to be true. See 
minor_changes:
  - Added asynchronous to organization task to speed up creation.
  - Update to controller_object_diff lookup plugin to better handle organizations.
...

2022-02-12 18:02 UTC, sean-m-sullivan commented
One last thought, should 'assign_galaxy_organizations_to_org' be set to true by default in the role defaults as that is what most would do, except for the first time creating new galaxy credentials?

2022-02-12 18:30 UTC, silvinux commented on roles/organizations/tasks/main.yml
> +    galaxy_credentials:                 "{{ (__controller_organizations_item.galaxy_organizations | default(omit)) if (assign_galaxy_organizations_to_org is defined and assign_galaxy_organizations_to
Sorry, I missed. I'll take a deeper look tomorrow. Thxs ;)

2022-02-12 18:46 UTC, silvinux commented
Regarding 

This is a chicken egg problem. We were discussiong it, and we think that should be not set. The organization is the object that everything should depend on, so basically I think we have this options:

1.- Create Organization, then create the credential and last the credential can be added  to the organization.
2.- Create just the galaxy credentials, then the organizations and last the other credentials.

It's tricky. 

We took the first option, and we've implemented first creating the organizations with variable `assign_galaxy_credentials_to_org` not set, then when the credentials have been created, the variable is set to true after you make sure that the credential is created. 

$ cat roles/controller_casc_implementation/tasks/organizations.yml
```
- name: Include Tasks to config galaxy credentials to Organizations
  include_tasks: organizations.yml
  vars:
    assign_galaxy_credentials_to_org: true
```

roles/controller_casc_implementation/tasks/credentials.yml
```
- name: Configure Controller Credentials | Launch credential creation
  import_role:
    name: redhat_cop.controller_configuration.credentials

- name: Include Tasks to config galaxy credentials to Organizations
  include_tasks: organizations.yml
  vars:
    assign_galaxy_credentials_to_org: true
```

2022-02-13 05:57 UTC, sean-m-sullivan commented on plugins/lookup/controller_object_diff.py
> +        # Set Keys to keep for each list. Depending on type
I just did a comparison to #270 and this looks to be duplicated still, I got that the text was identical sans an extra line at the end of file.

2022-02-14 17:09 UTC, Tompage1994 requested changes
Thanks for the contribution.

I'm not 100% sure I like the changes to placing in the galaxy credential here. Personally I usually follow a workflow of calling the credential role first and giving that a slimmed down set of vars (i.e. only the galaxy credentials) and then calling the organisation role before calling the credential role later in the usual way. I wonder whether it would be better, simpler, and prevent a breaking change, to simply update our examples with that workflow (and perhaps add some docs to it)

Regarding the async stuff I do like that, though I would like to see that against all of the roles rather than just some. If you could do that, that would be great.

Thanks

2022-02-15 16:10 UTC, djdanielsson reviewed
i have a couple of questions

2022-02-15 16:10 UTC, djdanielsson commented on roles/master_role_example/tasks/main.yml
> +    async: 1000
looks like your spacing is off here

2022-02-15 16:10 UTC, djdanielsson commented on roles/projects/tasks/main.yml
>  ...
did you mean to remove the async from projects?

2022-02-15 16:59 UTC, sean-m-sullivan commented on roles/projects/tasks/main.yml
>  ...
no, I had expected to update my merge before this got merged in, I'm working on variables for all the async to merge in, this will be fixed in another PR.

2022-02-15 19:44 UTC, merged

2022-02-16 14:09 UTC, silvinux commented
> 0% sure I like the change
I guess you are right, to keep the collection generic that var shouldn't be added. Either way organizations or credentials must be run twice.  cheers