Add organisation support to user creation
redhat-cop/automate_tower_genie_collections pull request #282
Opened 2022-03-14 15:52 UTC by ctodea

### What does this PR do?
Allow setting the organisation when creating users.

The awx collection already supports specifying the organization when creating users (see https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/user.py#L141).
 

### How should this be tested?
The change can easily be tested running the playbook below, on an automation controller. 
Before this PR, the `organization` field within `controller_user_accounts` would be ignored, and the user wouldn't be a member of any organization. Variable can be left empty, and has a ` | default(omit)`.

```
- name: Playbook to configure ansible controller
  hosts: automationcontroller
  vars:
    controller_validate_certs: false
    controller_hostname: aap00
    controller_username: admin
    controller_password: change_me
  collections:
    - awx.awx
    - redhat_cop.controller_configuration
  roles:
    - name: organizations
      vars:
        controller_organizations:
          - name: "evil_corp"
            custom_virtualenv: "/var/lib/awx/myvenv"
            max_hosts: 0
            state: present 

    - name: users
      vars:
        controller_user_accounts:
          - username: "ctodea" 
            email: "ctodea@redhat.com"
            state: present
            organization: "evil_corp" # this will make the user a member of the org
```

### Is there a relevant Issue open for this?
No

### Other Relevant info, PRs, etc.
N/A

2022-03-14 16:38 UTC, djdanielsson requested changes
please explain the logic before this is approved.

2022-03-14 16:38 UTC, djdanielsson commented on roles/users/tasks/main.yml
> +    organization:             "{{ __controller_user_accounts_item.organization | default(__controller_user_accounts_item.organization | default(omit)) }}"
I am not sure I understand the logic here, you are defaulting to __controller_user_accounts_item.organization which is the exact thing you have set as the main var then default omit. what is the point of the 2nd reference?

2022-03-14 16:42 UTC, Tompage1994 requested changes
Looks good. Just the one doc change and then this is good to go

2022-03-14 16:42 UTC, Tompage1994 commented on roles/users/README.md
> +|`organization`|""|no|str|The name of the organization the user belongs to|
Could you put a note in this to make clear that this will only work in awx.awx >= 20.0.0 and ansible.controller > 2.1.1 (there is no release on controller which has this implemented yet)

2022-03-14 17:32 UTC, sean-m-sullivan commented on roles/users/tasks/main.yml
> +    organization:             "{{ __controller_user_accounts_item.organization | default(__controller_user_accounts_item.organization | default(omit)) }}"
2nd defaults are for when its different from a simpler default vs the one from export. Currently a user created using your method above, does not have the org show up in the api or in the export, so its not needed. 
simplify to 
```
"{{ __controller_user_accounts_item.organization | default(omit) }}" 
```

2022-03-14 18:35 UTC, ctodea commented on roles/users/tasks/main.yml
> +    organization:             "{{ __controller_user_accounts_item.organization | default(__controller_user_accounts_item.organization | default(omit)) }}"
Fixed.

2022-03-14 20:00 UTC, sean-m-sullivan commented on roles/users/README.md
> +|`organization`|""|no|str|The name of the organization the user belongs to|
Use this code
```
|`organization`|""|no|str|The name of the organization the user belongs to.<br />Added in awx.awx >= 20.0.0 and ansible.controller >= 4.1.1|
```

2022-03-14 20:01 UTC, sean-m-sullivan commented
Please also add a fragment file under
https://github.com/redhat-cop/controller_configuration/tree/devel/changelogs/fragments

should be something along the lines of
```
minor_changes:
  - Allow setting the organisation when creating users.
```

2022-03-15 12:25 UTC, Tompage1994 approved these changes
LGTM

2022-03-15 13:06 UTC, djdanielsson approved these changes
LGTM

2022-03-15 13:06 UTC, merged