Added tasks and vars for EE's, teams, roles, etc, updated README, and…
redhat-cop/automate_tower_genie_collections pull request #315
Opened 2022-05-03 16:47 UTC by tonyreveal

… fixed tagging

### What does this PR do?
Brief explanation of the code or documentation change you've made

### How should this be tested?
Automated tests are preferred, but not always doable - especially for infrastructure. Include commands to run your new feature, and also post-run commands to validate that it worked. (please use code blocks to format code samples)

### Is there a relevant Issue open for this?
Provide a link to any open issues that describe the problem you are solving.
resolves #<number>

### Other Relevant info, PRs, etc.
Please provide link to other PRs that may be related (blocking, resolves, etc. etc.)

2022-05-03 18:38 UTC, djdanielsson requested changes
we require true or false, please correct all occurrences where you use yes or no. I haven't had time to look super close at everything else but that needs to be corrected.

2022-05-03 18:40 UTC, sean-m-sullivan commented on examples/templates/README.md
> +Controller Configuration
I like this write up, its a good, it covers everything, and goes into detail. 
We should move this into the examples folder though, not the template folder so its more visable.

2022-05-03 18:41 UTC, sean-m-sullivan commented on examples/templates/collections/requirements.yml
> +...
New line needed end of file

2022-05-03 18:41 UTC, sean-m-sullivan commented on examples/templates/controller_config.yml
> +#   - alltags
All is a default, and alltags are not mentioned in your readme, do we need an alltags?

2022-05-03 18:44 UTC, sean-m-sullivan commented on examples/templates/vars/controller_credential_types.yml
> -# Refer to https://github.com/redhat-cop/controller_configuration/tree/devel/roles/credential_types
Lets reset this file back to default, Its not passing lint, and should still be controller configuration

2022-05-03 18:45 UTC, sean-m-sullivan commented on examples/templates/vars/controller_ldap_configuration.json
> -// Refer to https://github.com/redhat-cop/controller_configuration/tree/devel/roles/settings
same lets reset all the variable files with the lint changes and name changes

2022-06-02 04:54 UTC, tonyreveal commented on examples/templates/controller_config.yml
> +#   - alltags
Yes, we need an alltags.  It's written with the never tag so that none of the collections roles execute by default.  The user can specify to run just one specific tag or multiple tags because everything else already exists.  Or they can use alltags to run everything.  I fixed the README

2022-06-02 04:55 UTC, tonyreveal commented on examples/templates/vars/controller_credential_types.yml
> -# Refer to https://github.com/redhat-cop/controller_configuration/tree/devel/roles/credential_types
It's passing lint now

2022-06-02 04:56 UTC, tonyreveal commented on examples/templates/vars/controller_ldap_configuration.json
> -// Refer to https://github.com/redhat-cop/controller_configuration/tree/devel/roles/settings
The only find in this file was no new line at end of file.  That's fixed.

2022-06-02 04:56 UTC, tonyreveal commented on examples/templates/collections/requirements.yml
> +...
Fixed

2022-06-02 04:57 UTC, tonyreveal commented on examples/templates/README.md
> +Controller Configuration
Your original request was to put it in the templates folder.  I can move it if desired.

2022-06-02 04:59 UTC, tonyreveal commented
I've verified all linting passes.  The only question is whether to leave this in the templates folder or move it to the examples folder.

2022-06-02 14:57 UTC, djdanielsson requested changes
I noticed some more things that need to be fixed

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/tasks/manage_organizations.yml
> +- name: Get list of organizations from Tower
this needs to be changed back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/tasks/manage_organizations.yml
> +    url:  "https://{{ controller_hostname }}/api/v2/organizations/"
I don't think we want 2 spaces here

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_credential_types.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/credential_types
this needs to be corrected

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_credentials.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/credentials
needs to be controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_groups.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/groups
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_hosts.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/hosts
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_inventories.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/inventories
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_inventory_sources.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/inventory_sources
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_job_templates.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/job_templates
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_labels.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/labels
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_ldap_configuration.json
> +// Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/settings
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_notification_templates.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/notification_templates
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_organizations.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/organizations
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_organizations_with_hub.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/organizations
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_projects.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/projects
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_schedules.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/schedules
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_users.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/users
back to controller

2022-06-02 14:57 UTC, djdanielsson commented on examples/templates/vars/controller_workflows.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/workflow_job_templates
back to controller

2022-06-02 15:47 UTC, tonyreveal commented on examples/templates/vars/controller_groups.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/groups
FIxed

2022-06-02 15:47 UTC, tonyreveal commented on examples/templates/vars/controller_groups.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/groups
FIxed

2022-06-02 15:47 UTC, tonyreveal commented on examples/templates/vars/controller_organizations_with_hub.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/organizations
FIxed

2022-06-02 15:47 UTC, tonyreveal commented on examples/templates/vars/controller_projects.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/projects
FIxed

2022-06-02 15:47 UTC, tonyreveal commented on examples/templates/vars/controller_schedules.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/schedules
FIxed

2022-06-02 15:47 UTC, tonyreveal commented on examples/templates/vars/controller_users.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/users
FIxed

2022-06-02 15:47 UTC, tonyreveal commented on examples/templates/vars/controller_workflows.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/workflow_job_templates
FIxed

2022-06-02 15:47 UTC, tonyreveal commented on examples/templates/vars/controller_credential_types.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/credential_types
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/vars/controller_hosts.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/hosts
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/vars/controller_inventory_sources.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/inventory_sources
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/vars/controller_labels.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/labels
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/vars/controller_notification_templates.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/notification_templates
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/vars/controller_organizations.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/organizations
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/vars/controller_ldap_configuration.json
> +// Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/settings
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/vars/controller_job_templates.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/job_templates
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/vars/controller_inventories.yml
> +# Refer to https://github.com/redhat-cop/tower_configuration/tree/devel/roles/inventories
FIxed

2022-06-02 15:48 UTC, tonyreveal commented on examples/templates/tasks/manage_organizations.yml
> +    url:  "https://{{ controller_hostname }}/api/v2/organizations/"
FIxed

2022-06-02 15:49 UTC, tonyreveal commented on examples/templates/tasks/manage_organizations.yml
> +- name: Get list of organizations from Tower
Fixed

2022-06-02 15:58 UTC, djdanielsson approved these changes
I am not seeing anything jump out at me, @sean-m-sullivan see anything else that needs to get changed or do we want to merge it?

2022-06-03 16:07 UTC, sean-m-sullivan approved these changes
This is a good template, but a lot to look over, Thanks for the Update!

2022-06-03 16:07 UTC, merged