Let the collection to use both awx.awx and ansible.controller collections, as per user decision
redhat-cop/automate_tower_genie_collections pull request #351
Opened 2022-09-09 09:49 UTC by ivarmu

add variable to set the plugin name to use everywhere

### What does this PR do?
Right now, the tasks in filetree_create and object_diff roles are using the `ansible.controller` collection to make use of the `controller_api` plugin, so anyone trying to use the `awx.awx` collection will get in trouble as the `ansible.controller` collection should not be present. To let the end users to chose freely what collection they want to use, I've modified the code to get that collection name from a variable, which must be defined with the correct value to work successfully.

### How should this be tested?
```
$ cat filetree_create.yml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: "{{ vault_controller_hostname }}"
    controller_username: "{{ vault_controller_username }}"
    controller_password: "{{ vault_controller_password }}"
    controller_validate_certs: "{{ vault_controller_validate_certs }}"
    controller_api_plugin: "ansible.controller.controller_api"
  pre_tasks:
    - name: "Check if the required input variables are present"
      assert:
        that:
          - input_tag is defined
          - (input_tag | type_debug) == 'list'
        fail_msg: 'A variable called ''input_tag'' of type ''list'' is needed: -e ''{input_tag: [organizations, projects]}'''
        quiet: true

    - name: "Check if the required input values are correct"
      assert:
        that:
          - tag_item in valid_tags
        fail_msg: "The valid tags are the following ones: {{ valid_tags | join(', ') }}"
        quiet: true
      loop: "{{ input_tag }}"
      loop_control:
        loop_var: tag_item
  roles:
    - redhat_cop.controller_configuration.filetree_create
...
$ ansible-playbook filetree_create.yml -e '{input_tag: [inventory], output_path: ~/iam/filetree_create.2.1.7 }'
```

### Is there a relevant Issue open for this?
No issue opened for this.

### Other Relevant info, PRs, etc.
N/A

2022-09-09 10:25 UTC, ivarmu commented
@sean-m-sullivan @Tompage1994 @djdanielsson I think it would be a good idea to have a new release based on that PR, as the current version is tied to the `ansible.controller`collection and will not work if the user only {wants to,can} have `awx.awx` collection installed. What do you think?

2022-09-09 10:31 UTC, Tompage1994 requested changes
I don't necessarily like this solution but it may be the best we can do. I'm not sure if there is some magic we could do to look up what collection we are using. 

That said, I'm happy to go with this, at least for now. My only thought is that we should probably default to ansible.controller rather than awx.awx.

2022-09-09 10:48 UTC, ivarmu commented
> I don't necessarily like this solution but it may be the best we can do. I'm not sure if there is some magic we could do to look up what collection we are using.
> 
> That said, I'm happy to go with this, at least for now. My only thought is that we should probably default to ansible.controller rather than awx.awx.

I've set it to `awx.awx` to be consistent with the collection already used in the example two lines after my addition. We can change it if you preffer, but the rest of the examples and documentation is based in `awx.awx` as well...

2022-09-09 11:22 UTC, ivarmu commented
If you agree, I could add this to automatically detect what collection is installed, and default to `ansible.controller` if both of them are present:

https://github.com/redhat-cop/controller_configuration/issues/341

2022-09-09 12:37 UTC, ivarmu commented
> If you agree, I could add this to automatically detect what collection is installed, and default to `ansible.controller` if both of them are present:
> 
> https://docs.ansible.com/ansible/latest/collections/community/general/collection_version_lookup.html
> 
> or the following to run `ansible-galaxy collection list | grep ansible.controller` if we don't want to depend on `community.general`:
> 
> https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pipe_lookup.html#ansible-collections-ansible-builtin-pipe-lookup

To avoid depending on `community.general` collection, I can integrate the following code if it look good for you:

```
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - block:
        - name: "Check if the collection ansible.controller is installed"
          set_fact:
            ansible_controller_collection_installed: "{{ lookup('pipe', 'ansible-galaxy collection list | grep -i ansible.controllersss') }}"
      rescue:
        - name: "Check if the collection awx.awx is installed"
          set_fact:
            awx_awx_collection_installed: "{{ lookup('pipe', 'ansible-galaxy collection list | grep -i awx.awx') }}"
    - name: "Set the collection providing the controller_api lookup plugin"
      set_fact:
        collection_name: "{{ ('ansible.controller.controller_api' if ansible_controller_collection_installed is defined) | default('awx.awx.controller_api' if awx_awx_collection_installed is defined) | default('NONE') }}"
    - debug:
        msg:
          - "collection_name: {{ collection_name }}"
...
```

2022-09-09 14:57 UTC, djdanielsson commented
I like that solution to figure out which collection is being used

2022-09-09 20:45 UTC, ivarmu commented
On Monday I'm working on it :blush:

2022-09-12 13:38 UTC, sean-m-sullivan commented on plugins/lookup/controller_object_diff.py
> -    controller_organization_id: "{{ lookup('awx.awx.controller_api', 'organizations', query_params={ 'name': 'Default' },
Lets leave this as is, as the plugin can be used outside the roles, the plugin itself should be self documenting.

2022-09-12 13:39 UTC, sean-m-sullivan commented on roles/filetree_create/README.md
> +| **`controller_api_plugin`**: | N/A | yes | Full path for the controller_api_plugin to be used. <br/> Can have two possible values: <br/>&nbsp;&nbsp;- awx.awx.controller_api             # For the co
in addition to updating the readme's. Can we put a default value for this in each of the roles. So if they do not use our default playbooks with detection it doesn't fail due to the plugin not being defined. Should default to the ansible.controller collection version.

2022-09-13 15:06 UTC, ivarmu commented on plugins/lookup/controller_object_diff.py
> -    controller_organization_id: "{{ lookup('awx.awx.controller_api', 'organizations', query_params={ 'name': 'Default' },
Done

2022-09-13 15:07 UTC, ivarmu commented on roles/filetree_create/README.md
> +| **`controller_api_plugin`**: | N/A | yes | Full path for the controller_api_plugin to be used. <br/> Can have two possible values: <br/>&nbsp;&nbsp;- awx.awx.controller_api             # For the co
I've added the default values for both `filetree_create` and `object_diff` roles.

2022-09-15 06:53 UTC, ivarmu commented on roles/filetree_create/README.md
> +| **`controller_api_plugin`**: | N/A | yes | Full path for the controller_api_plugin to be used. <br/> Can have two possible values: <br/>&nbsp;&nbsp;- awx.awx.controller_api             # For the co
I was thinking that a better place to add the auto-detection for the plugin to be used should be the `main.yml` of each role, so the default value shouldn't be needed. I've updated the PR with these changes.

2022-09-21 09:23 UTC, ivarmu commented
I'm not sure if there's anything pending in this PR.

2022-09-22 01:50 UTC, sean-m-sullivan approved these changes
LGTM, thanks for making the changes.

2022-09-22 02:04 UTC, merged