Update ansible-lint version and fix lint errors
redhat-cop/automate_tower_genie_collections pull request #391
Opened 2022-10-19 21:20 UTC by branic

### What does this PR do?

Updates ansible-lint to version 6.8.2 and fixes new found linting errors.

The `fqcn[action]` check has also been disabled as the collection depends on either the `awx.awx` or `ansible.controller` collection so the FQCN of the modules cannot be specified.

### How should this be tested?

Automated tests are preferred, but not always doable - especially for infrastructure. Include commands to run your new feature, and also post-run commands to validate that it worked. (please use code blocks to format code samples)

### Is there a relevant Issue open for this?

No

### Other Relevant info, PRs, etc

Nnoe

2022-10-20 05:31 UTC, ivarmu commented on roles/filetree_create/tasks/inventory.yml
> +- name: "Create the <ORGANIZATION_NAME>/inventories output directory for inventories in {{ output_path | regex_replace('/', '_') }}"
output_path can't be regex_replaced entirely because it contains the full (relative) path, which must show the directories correctly. That treatment has been done at other places, where the output_path is constructed.

2022-10-20 05:31 UTC, ivarmu commented on roles/filetree_create/tasks/inventory.yml
> +- name: "Add current inventories to the <ORGANIZATION_NAME>/inventories output yaml file in {{ output_path | regex_replace('/', '_') }}"
output_path can't be regex_replaced entirely because it contains the full (relative) path, which must show the directories correctly. That treatment has been done at other places, where the output_path is constructed.

2022-10-20 05:36 UTC, ivarmu requested changes
LGTM. Only make the requested changes to let the paths show correctly in the tasks' names.

Great job!

2022-10-20 22:39 UTC, branic commented on roles/filetree_create/tasks/inventory.yml
> +- name: "Add current inventories to the <ORGANIZATION_NAME>/inventories output yaml file in {{ output_path | regex_replace('/', '_') }}"
Removed the regex_replace where used in the name of a task.

2022-10-20 22:41 UTC, branic commented on roles/filetree_create/tasks/inventory.yml
> +- name: "Create the <ORGANIZATION_NAME>/inventories output directory for inventories in {{ output_path | regex_replace('/', '_') }}"
I've removed the `regex_replace` for `output_path` when it is used in the name of a task.

2022-10-20 23:19 UTC, silvinux approved these changes
LGTM

2022-10-20 23:30 UTC, djdanielsson commented
I have set it to merge once @ivarmu approves the fixes

2022-10-21 07:02 UTC, ivarmu approved these changes
Thanks for these changes!

2022-10-21 07:02 UTC, merged