Create bug_report.md
redhat-cop/automate_tower_genie_collections pull request #414
Opened 2022-11-17 22:50 UTC by djdanielsson

### What does this PR do?

adds bug report template

### How should this be tested?

none

### Is there a relevant Issue open for this?

none

### Other Relevant info, PRs, etc

none

2022-11-17 22:52 UTC, djdanielsson commented
I just tweaked a copy of the ansible-lint bug report template, looking for what other content we should add in ours.

2022-11-17 23:01 UTC, branic requested changes

2022-11-17 23:01 UTC, branic commented on .github/ISSUE_TEMPLATE/bug_report.md
> +```
You missed including this:

`[minimum complete verifiable example]: http://stackoverflow.com/help/mcve`

This allows the text on line 61 to be a hyperlink. I think it is good that we include the link.

2022-11-17 23:06 UTC, djdanielsson commented on .github/ISSUE_TEMPLATE/bug_report.md
> +```
thanks, added it back in

2022-11-17 23:07 UTC, branic approved these changes
LGTM

2022-11-18 04:29 UTC, sean-m-sullivan approved these changes
lgtm

2022-11-18 04:29 UTC, merged