[filetree_read role] - Added controller_location variable to handle multiple sites and loop…
redhat-cop/automate_tower_genie_collections pull request #415
Opened 2022-11-19 13:32 UTC by silvinux

# What does this PR do?

- Added controller_location variable in filetree_read role  to handle multiple sites on an Active/Passive architecture[1] over the Controller objects[2] that might require different values  depend on site.
[2].-[Ref Arch AAP](https://access.redhat.com/webassets/avalon/d/Reference_Architectures-2021-Deploying_Ansible_Automation_Platform_2.1-en-US/images/6e0171f99b891d6c50ebf14af768b576/overview.png)

```
$ tree orgs_vars/org-test/env/dev-site/
├── controller_credentials.d
├── controller_execution_environments.d
├── controller_hosts.d
├── controller_instance_groups.d
├── controller_inventory_sources.d
└── controller_settings.d
```
-  Added loop_var control to all loops in filetree_read role tasks.

# How should this be tested?

- Deploy two controllers and two automationhubs.
```
$ cat inventory 
[dev-site1]
lb-ctr-dev-site1.bcnconsulting.com
[dev-site2]
lb-ctr-dev-site2.bcnconsulting.com

[dev:children]
dev-site1
dev-site2

$ cat group_vars/dev/configure_connection_controller_credentials.yml 
---
vault_controller_username: 'org-test'
vault_controller_password: 'password'
vault_controller_validate_certs: false
...
$ cat group_vars/dev-site1/configure_connection_controller_credentials.yml 
---
vault_controller_hostname: "{{ groups['dev-site1'][0] }}"
...

$ cat group_vars/dev-site2/configure_connection_controller_credentials.yml 
---
vault_controller_hostname: "{{ groups['dev-site2'][0] }}"
...
```
- Add credential definition under the directory structure 
```
$ cat orgs_vars/org-test/env/dev-site/controller_credentials.d/controller_credentials_registry.yaml
---
controller_credentials:
  - name: "{{ orgs }} {{ env }} {{ controller_location }} Automation Private Hub Container Registry"
    description: "Credential to connect to Container Registry at AtomationHub Private"
    credential_type: "Container Registry"
    organization: "{{ orgs }}"
    inputs:
      username: "organization-admin"
      password: "password"
      host: demo-hub1-dev.bcnconsulting.com
      verify_ssl: false
    controller_location: site1

  - name: "{{ orgs }} {{ env }} {{ controller_location }} Automation Private Hub Container Registry"
    description: "Credential to connect to Container Registry at AtomationHub Private"
    credential_type: "Container Registry"
    organization: "{{ orgs }}"
    inputs:
      username: "organization-admin"
      password: "password"
      host: demo-hub2-dev.bcnconsulting.com
      verify_ssl: false
    controller_location: site2

```
- Apply the configuration in one site a time
```
$ ansible-navigator run casc_ctrl_config.yml -i inventory -l dev-site1 -e '{orgs: org-test, dir_orgs_vars: orgs_vars, env: dev-site, controller_location: site1}' -m stdout --eei lb-hub-dev-site1.bcnconsulting.com/ee-casc:latest --pull-arguments=--tls-verify=false --vault-password-file .vault_password --tags credentials 

$ ansible-navigator run casc_ctrl_config.yml -i inventory -l dev-site2 -e '{orgs: org-test, dir_orgs_vars: orgs_vars, env: dev-site, controller_location: site1}' -m stdout --eei lb-hub-dev-site2.bcnconsulting.com/ee-casc:latest --pull-arguments=--tls-verify=false --vault-password-file .vault_password --tags credentials  
```

2022-11-19 14:05 UTC, ivarmu requested changes
Let's correct the indentation and change the `when` location to be just the line after the `block:` one

You could also add to the PR description the substitution of every `item` loop variable to avoid conflicts.

Great job @silvinux !!!

2022-11-19 14:05 UTC, ivarmu commented on roles/filetree_read/tasks/credentials.yml
> +  - name: "Populate Credentials list by _common objects"
Let's correct the indentation and change the `when` location to be just the line after the `block:` one

2022-11-19 14:05 UTC, ivarmu commented on roles/filetree_read/tasks/execution_environments.yml
> +  - name: "Populate Execution Environments list by _common objects"
Let's correct the indentation and change the `when` location to be just the line after the `block:` one

2022-11-19 14:05 UTC, ivarmu commented on roles/filetree_read/tasks/hosts.yml
> +  - name: "Populate Hosts list by _common objects"
Let's correct the indentation and change the `when` location to be just the line after the `block:` one

2022-11-19 14:05 UTC, ivarmu commented on roles/filetree_read/tasks/instance_groups.yml
> +  - name: "Populate Instance Groups list by _common objects"
Let's correct the indentation and change the `when` location to be just the line after the `block:` one

2022-11-19 14:05 UTC, ivarmu commented on roles/filetree_read/tasks/inventory_sources.yml
> +  - name: "Populate Inventory Sources list by _common objects"
Let's correct the indentation and change the `when` location to be just the line after the `block:` one

2022-11-19 14:05 UTC, ivarmu commented on roles/filetree_read/tasks/settings.yml
> +  - name: "Populate Settings list by _common objects"
Let's correct the indentation and change the `when` location to be just the line after the `block:` one

2022-11-19 20:44 UTC, sean-m-sullivan approved these changes
This looks good, I like the addition of loop vars, it got a little hard to read when mixing the two.

2022-11-19 20:46 UTC, sean-m-sullivan commented
Agree on the when after block, its the new standard to use and we need to do that elsewhere as well.

2022-11-21 07:22 UTC, ivarmu approved these changes
LGTM. Great job!!! Many thanks!

2022-11-21 07:22 UTC, merged