Fixed typos and improved some sentences.
redhat-cop/automate_tower_genie_collections pull request #450
Opened 2022-12-19 14:52 UTC by tuxpreacher

# What does this PR do?

Fixes some typos and poorly worded sentences.

# How should this be tested?

It's just text changes, no code.

# Is there a relevant Issue open for this?

No.

# Other Relevant info, PRs, etc

Is the uppercase use of "REQUIREMENTS" a standard in redhat_cop? I changed it to "Requirements", feel free to change back.

2022-12-19 14:58 UTC, djdanielsson requested changes
please add a changelog note about this change

2022-12-20 10:44 UTC, Tompage1994 approved these changes

2022-12-20 11:09 UTC, tuxpreacher commented
> please add a changelog note about this change

Done.

2022-12-20 14:06 UTC, djdanielsson approved these changes
LGTM

2022-12-20 14:06 UTC, merged