Allow state to be undefined on workflow_job_templates when  using simplified_workflow_nodes
redhat-cop/automate_tower_genie_collections pull request #469
Opened 2023-01-17 03:41 UTC by spyrexd

# What does this PR do?

The `state` key is optional for workflow_job_templates unless you are using simplified_workflow_nodes.
This change allows the state key to remain optional when using simplified_workflow_nodes.

# How should this be tested?

Automated tests have been added

# Is there a relevant Issue open for this?

resolves #[297]

# Other Relevant info, PRs, etc

2023-01-17 08:55 UTC, silvinux reviewed
LGTM!

2023-01-17 10:10 UTC, Tompage1994 requested changes

2023-01-17 10:10 UTC, Tompage1994 commented on roles/workflow_job_templates/tasks/main.yml
> +    - __workflow_loop_item.state is undefined or __workflow_loop_item.state == "present"
I think this isn't the clearest like this. Would it be better to set this as 
```
__workflow_loop_item.state != 'absent'
```

2023-01-17 10:31 UTC, adonisgarciac commented on roles/workflow_job_templates/tasks/main.yml
> +    - __workflow_loop_item.state is undefined or __workflow_loop_item.state == "present"
I think it will not work because state is not defined by default in objects within configuration as code. State = present is  the default value, this PR try to remove the dependence of declare the state of workflows. With your solution, it will fail with an undefined variable.

2023-01-17 10:38 UTC, Tompage1994 commented on roles/workflow_job_templates/tasks/main.yml
> +    - __workflow_loop_item.state is undefined or __workflow_loop_item.state == "present"
In that case you could do:

```
- (__workflow_loop_item.state | default('present')) == "present"
```

Just thinking it otherwise isn't entirely clear

2023-01-17 17:05 UTC, spyrexd commented on roles/workflow_job_templates/tasks/main.yml
> +    - __workflow_loop_item.state is undefined or __workflow_loop_item.state == "present"
Pushed changes to the way the default value is evaluated.

2023-01-18 02:25 UTC, sean-m-sullivan approved these changes
LGTM, good change and catch.

2023-01-18 10:26 UTC, Tompage1994 approved these changes

2023-01-18 10:26 UTC, merged