Role updates
redhat-cop/automate_tower_genie_collections pull request #556
Opened 2023-03-28 14:36 UTC by sean-m-sullivan

# What does this PR do?

Adds two roles and updates options on various roles in order to bring the collection to parity with the awx.awx collection.

# How should this be tested?

Automated tests have been created for the roles. 

Currently working on getting the tests working, but its in a place where its almost done and ready for review.

2023-03-28 15:06 UTC, djdanielsson reviewed
what is the point of bulk hosts? wouldn't it be better to users them into inventory source by file and manage the hosts that way?

2023-03-28 15:09 UTC, djdanielsson requested changes
I also am not sure what I think of bulk launching jobs, but that one I am less against then hosts.

2023-03-29 09:24 UTC, Tompage1994 requested changes
A few changes needed

2023-03-29 09:24 UTC, Tompage1994 commented on roles/bulk_host_create/README.md
> +|`controller_************`|`see below`|yes|Data structure describing your organization or organizations Described below.||
The ******* should be filled in as `controller_bulk_hosts`

2023-03-29 09:24 UTC, Tompage1994 commented on roles/bulk_host_create/README.md
> +|`controller_************`|`see below`|yes|Data structure describing your organization or organizations Described below.||
And the same for all the other instances of ***** below

2023-03-29 09:24 UTC, Tompage1994 commented on roles/bulk_host_create/meta/argument_specs.yml
> +        # options:
Can you remove this commented section as thats not relevant to this arg_spec.

You could leave in inventory and add hosts if you want but we aren't using it at the moment so it's not really a bother

2023-03-29 09:24 UTC, Tompage1994 commented on roles/bulk_job_launch/README.md
> +|`controller_************`|`see below`|yes|Data structure describing your organization or organizations Described below.||
Same thing with ****** again

2023-03-29 09:24 UTC, Tompage1994 commented on roles/bulk_job_launch/meta/argument_specs.yml
> +        # options:
Again, please remove commented section unless its specific for this role

2023-03-29 09:24 UTC, Tompage1994 commented on changelogs/fragments/role_updates.yml
> +  - Added new_name option to the roles applications, credential_types, execution_environments, inventories, projects, users.
There was also new_username and the changes in workflow_job_templates

2023-03-29 09:25 UTC, Tompage1994 commented
> what is the point of bulk hosts? wouldn't it be better to push users into inventory source by file and manage the hosts that way?

These are just the new modules in awx.awx > https://github.com/ansible/awx/tree/devel/awx_collection/plugins/modules

2023-03-31 12:59 UTC, djdanielsson commented
I will approve once the changes Tom requested are done

2023-04-01 20:09 UTC, sean-m-sullivan commented on roles/bulk_host_create/README.md
> +|`controller_************`|`see below`|yes|Data structure describing your organization or organizations Described below.||
Fixed

2023-04-01 20:09 UTC, sean-m-sullivan commented on roles/bulk_host_create/meta/argument_specs.yml
> +        # options:
Fixed

2023-04-01 20:10 UTC, sean-m-sullivan commented on roles/bulk_job_launch/README.md
> +|`controller_************`|`see below`|yes|Data structure describing your organization or organizations Described below.||
Fixed

2023-04-01 20:10 UTC, sean-m-sullivan commented on roles/bulk_job_launch/meta/argument_specs.yml
> +        # options:
Fixed

2023-04-01 20:11 UTC, sean-m-sullivan commented on changelogs/fragments/role_updates.yml
> +  - Added new_name option to the roles applications, credential_types, execution_environments, inventories, projects, users.
Updated

2023-04-01 20:12 UTC, djdanielsson approved these changes

2023-04-02 14:46 UTC, merged