Add option to roles to enforce defaults
redhat-cop/automate_tower_genie_collections pull request #567
Opened 2023-04-08 22:12 UTC by sean-m-sullivan

# What does this PR do?
As per the discussion an option has been added to multiple roles to enforce defaults. 
This option enforces module/api defaults in order to prevent config drift. This makes it so if an option is NOT specified in a configuration it enforces the default value. It is not enabled by default.

I have started with two roles that have multiple options enabled for review. The default environment is not set in orgs as there is an underlying issue with the module and the API where the default value is null, and its hard to pass that through the role->module->api.

I did try to do inline if/else like we do galaxy creds and it did not work
I tried to make my own default filter, but it does not allow for a variable to not be defined. 
In the end I settled on a simple lookup plugin to perform the if/else logic and thus provide the default with one value to then work on.

# How should this be tested?
This has been turned on in automated tests

# Is there a relevant Issue open for this?
#495

2023-04-08 22:33 UTC, djdanielsson requested changes
Questions

2023-04-08 22:33 UTC, djdanielsson commented on changelogs/fragments/enforce_defaults.yml
> +minor_changes:
I wouldn't call this a minor change I think

2023-04-08 22:33 UTC, djdanielsson commented on roles/applications/tasks/main.yml
> +    description:                    "{{ __application_item.description | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_applications_enforc
Do we want that final true?

2023-04-09 00:32 UTC, sean-m-sullivan commented on roles/applications/tasks/main.yml
> +    description:                    "{{ __application_item.description | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_applications_enforc
The final true is the same as it was before the 
| default(omit, true)
its now
| default(lookup, true)

2023-04-09 00:35 UTC, sean-m-sullivan commented on changelogs/fragments/enforce_defaults.yml
> +minor_changes:
Its a feature addition that isn't a breaking change, 
https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst#changelog-fragment-categories

minor_changes
    This category should mention all new features, like plugin or module options. This section should not appear in patch releases according to semantic versioning.
    
It's a new feature added, an option.

2023-04-09 00:35 UTC, sean-m-sullivan commented on changelogs/fragments/enforce_defaults.yml
> +minor_changes:
If I were to have made it NON optional, enforced by default, I'd say major breaking change.

2023-04-09 00:45 UTC, djdanielsson commented on roles/applications/tasks/main.yml
> +    description:                    "{{ __application_item.description | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_applications_enforc
I thought the decision was to remove the true to all of them though?

2023-04-09 01:00 UTC, sean-m-sullivan commented on roles/applications/tasks/main.yml
> +    description:                    "{{ __application_item.description | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_applications_enforc
I've been using this as a reference
https://github.com/redhat-cop/controller_configuration/issues/132
The default omit true or false is a weird beast, if you remove the true, then it sometimes sends strings "" to the option, which with defaulted values is what we wanted, but with True it sets null, which has been the past behavior, I believe if we did remove true, it would be a breaking change at this point. 

The previous conversation in the discussion linked in the PR, was more about how to go about doing the default values or the "Enforced" state, which we've bypassed the need to remove the true, as we have it the OLD way AND the Enforced way using this plugin.

2023-04-09 01:20 UTC, djdanielsson approved these changes
Can't wait to try it out

2023-04-10 20:07 UTC, merged