Change lookup to query to ensure list
redhat-cop/automate_tower_genie_collections pull request #647
Opened 2023-07-13 08:57 UTC by Rickmarges

# What does this PR do?

When first configuring an organization with only 1 inventory defined, the configuration fails with the message:
`argument 'controller_inventories' is of type <class 'dict'> and we were unable to convert to list`

The diff_role tasks use the `lookup` plugin to calculate the differences, which doesn't necessarily create a list when it recieves one item. This change will move from `lookup` to `query`, which will always return a list

# How should this be tested?

1. Create an empty organization (without inventories)
2. Define 1 inventory for created organization
3. Run the configuraion with diff_role and `with_present: true`

# Other Relevant info, PRs, etc

https://docs.ansible.com/ansible/latest/plugins/lookup.html#forcing-lookups-to-return-lists-query-and-wantlist-true

2023-07-13 09:38 UTC, Rickmarges commented
We're still testing this further. We ran into some issues, but are not yet sure if they're related to this.
I will post an update ASAP

2023-07-13 14:16 UTC, Rickmarges commented
So, I've investigated the issue a bit more. Due to the last return statement (`return [difference]`) in combination with the `query` plugin from Ansible, caused certain lists to be set to a nested loop (`[[...]]`) instead of a single one (`[...]`).

With the currently added 2 commits, this issue should be resolved. And in my opinion this is ready to be merged once approved :)

2023-07-14 07:06 UTC, ivarmu approved these changes
LGTM

2023-07-16 05:36 UTC, sean-m-sullivan approved these changes
@ivarmu this looks good, looks like we need a changelog though as this is a breaking change, as well as the present/compare list bugfix,

2023-07-16 05:36 UTC, sean-m-sullivan requested changes
Changelog needed,

2023-07-17 15:27 UTC, sean-m-sullivan approved these changes

2023-07-17 15:28 UTC, merged