fixed collection detection and exporting job templates issues
redhat-cop/automate_tower_genie_collections pull request #650
Opened 2023-07-17 11:04 UTC by ivarmu

# What does this PR do?
Fixed collection detection and exporting job templates issues with missing inputs.

# How should this be tested?
Automatic tests.

# Is there a relevant Issue open for this?
N/A

# Other Relevant info, PRs, etc
N/A

2023-07-17 15:21 UTC, silvinux requested changes
Pre-commit is failing. Probably is when escaping the characters.

2023-07-18 14:06 UTC, silvinux approved these changes
LGTM!

2023-07-18 15:37 UTC, Tompage1994 commented
Can you please add a changelog fragment here

2023-07-18 15:37 UTC, Tompage1994 requested changes
Can you please add a changelog fragment here

2023-07-19 14:58 UTC, Tompage1994 requested changes
Just one fix needed

2023-07-19 14:58 UTC, Tompage1994 commented on changelogs/fragments/filetree_create_bugfix.yml
> +  - When importing the exported settings, fields like `AUTOMATION_ANALYTICS_LAST_GATHER: 2023-07-17T13:22:06.445818Z` caused problems with the multiple `:`.
```suggestion
  - "When importing the exported settings, fields like `AUTOMATION_ANALYTICS_LAST_GATHER: 2023-07-17T13:22:06.445818Z` caused problems with the multiple `:`."
```

The pre-commit is failing because of this line because theres a `:` it interprets it weirdly. Putting in quotes like this *should* fix it

2023-07-20 14:58 UTC, ivarmu commented
Temporarily fixed an error when installing docker-compose using pip (see https://stackoverflow.com/questions/76708329/docker-compose-no-longer-building-image-attributeerror-cython-sources for more information)

2023-07-21 00:46 UTC, sean-m-sullivan approved these changes
Thank you, I expected 6.0.1 to be out to fix this, but evidently not. 

Came back tonight to explicitly address this and the other issue.

2023-07-21 00:46 UTC, merged

2023-07-21 06:57 UTC, ivarmu commented
> Thank you, I expected 6.0.1 to be out to fix this, but evidently not.
> 
> Came back tonight to explicitly address this and the other issue.

The problem with `pyyaml==6.0.1` is the following:
```
ERROR: Cannot install docker-compose==1.1.0, docker-compose==1.10.0, docker-compose==1.10.1, docker-compose==1.11.0, docker-compose==1.11.1, docker-compose==1.11.2, docker-compose==1.12.0, docker-compose==1.13.0, docker-compose==1.14.0, docker-compose==1.15.0, docker-compose==1.16.0, docker-compose==1.16.1, docker-compose==1.17.0, docker-compose==1.17.1, docker-compose==1.18.0, docker-compose==1.19.0, docker-compose==1.2.0, docker-compose==1.20.0, docker-compose==1.20.1, docker-compose==1.21.0, docker-compose==1.21.1, docker-compose==1.21.2, docker-compose==1.22.0, docker-compose==1.23.0, docker-compose==1.23.1, docker-compose==1.23.2, docker-compose==1.24.0, docker-compose==1.24.1, docker-compose==1.25.0, docker-compose==1.25.1, docker-compose==1.25.2, docker-compose==1.25.3, docker-compose==1.25.4, docker-compose==1.25.5, docker-compose==1.26.0, docker-compose==1.26.1, docker-compose==1.26.2, docker-compose==1.27.0, docker-compose==1.27.1, docker-compose==1.27.2, docker-compose==1.27.3, docker-compose==1.27.4, docker-compose==1.28.0, docker-compose==1.28.2, docker-compose==1.28.3, docker-compose==1.28.4, docker-compose==1.28.5, docker-compose==1.28.6, docker-compose==1.29.0, docker-compose==1.29.1, docker-compose==1.29.2, docker-compose==1.3.0, docker-compose==1.3.1, docker-compose==1.3.2, docker-compose==1.3.3, docker-compose==1.4.0, docker-compose==1.4.1, docker-compose==1.4.2, docker-compose==1.5.0, docker-compose==1.5.1, docker-compose==1.5.2, docker-compose==1.6.0, docker-compose==1.6.1, docker-compose==1.6.2, docker-compose==1.7.0, docker-compose==1.7.1, docker-compose==1.8.0, docker-compose==1.8.1, docker-compose==1.9.0 and pyyaml==6.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pyyaml==6.0.1
    docker-compose 1.29.2 depends on PyYAML<6 and >=3.10
    The user requested pyyaml==6.0.1
    docker-compose 1.29.1 depends on PyYAML<6 and >=3.10
    The user requested pyyaml==6.0.1
    docker-compose 1.29.0 depends on PyYAML<6 and >=3.10
    The user requested pyyaml==6.0.1
    docker-compose 1.28.6 depends on PyYAML<6 and >=3.10
...
```

2023-07-21 14:02 UTC, sean-m-sullivan commented
No, i meant that pyyaml was causing issues in other places with not being able to installed via pip and a wheel error on 6.0.0, then after that, you up to 6.0.1 and docker-compose starts Another error!, its just been a week where pyyaml broke likely thousands of pipelines worldwide.