Deduplicate role task in roles role
redhat-cop/automate_tower_genie_collections pull request #662
Opened 2023-08-01 15:29 UTC by Tompage1994

# What does this PR do?
De-duplicates the role task in the roles role by using defaults and a more clever loop

# How should this be tested?
CI already added

# Is there a relevant Issue open for this?

resolves #661

# Other Relevant info, PRs, etc
There hasn't been a release since the PR which this is updating so no additional changelog required.

2023-08-01 15:49 UTC, djdanielsson approved these changes
LGTM

2023-08-01 17:22 UTC, ivarmu approved these changes
Looks better, but there's a situation that wouldn't be desired... if the input contains the following... it would silently bypass the wrong formatted entry (it is missing both `role` and `roles` parameters):

```
controller_roles:
  - team: "team1"
    credential: "credential1"
```

It's not a stopper, but may need to add an extra check for that situation...

2023-08-01 17:25 UTC, ivarmu requested changes

2023-08-01 17:25 UTC, ivarmu commented on roles/roles/tasks/main.yml
> -    ansible_async_dir: '{{ controller_configuration_async_dir }}'
Could you maintain these lines?

2023-08-02 06:54 UTC, ivarmu commented
> Looks better, but there's a situation that wouldn't be desired... if the input contains the following... it would silently bypass the wrong formatted entry (it is missing both `role` and `roles` parameters):
> 
> ```
> controller_roles:
>   - team: "team1"
>     credential: "credential1"
> ```
> 
> It's not a stopper, but may need to add an extra check for that situation...

Adding the following `fail` task would be enough to raise a failure when the input items has a lack of both `role` and `roles` fields:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - data:
        - name: row1
          roles:
            - role1
            - role2
        - name: row2
          role: roleA
        - name: row3
  tasks:
    - fail:
        msg: "The following input is incomplete: {{ current_bad_input }}"
      vars:
        bad_input: "{{ data | selectattr('role', 'undefined') | selectattr('roles', 'undefined') }}"
      loop: "{{ bad_input }}"
      loop_control:
        loop_var: current_bad_input

    - debug:
        msg:
          - "{{ item.1 if item.1 is defined else item.role }}"
      loop: "{{ (data | selectattr('role', 'defined')) + (data | subelements(['roles'], skip_missing=true)) }}"
...
```

What do you think?

2023-08-02 07:57 UTC, Tompage1994 commented
> > Looks better, but there's a situation that wouldn't be desired... if the input contains the following... it would silently bypass the wrong formatted entry (it is missing both `role` and `roles` parameters):
> > ```
> > controller_roles:
> >   - team: "team1"
> >     credential: "credential1"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's not a stopper, but may need to add an extra check for that situation...
> 
> Adding the following `fail` task would be enough to raise a failure when the input items has a lack of both `role` and `roles` fields:
> 
> ```yaml
> ---
> - hosts: localhost
>   connection: local
>   gather_facts: false
>   vars:
>     - data:
>         - name: row1
>           roles:
>             - role1
>             - role2
>         - name: row2
>           role: roleA
>         - name: row3
>   tasks:
>     - fail:
>         msg: "The following input is incomplete: {{ current_bad_input }}"
>       vars:
>         bad_input: "{{ data | selectattr('role', 'undefined') | selectattr('roles', 'undefined') }}"
>       loop: "{{ bad_input }}"
>       loop_control:
>         loop_var: current_bad_input
> 
>     - debug:
>         msg:
>           - "{{ item.1 if item.1 is defined else item.role }}"
>       loop: "{{ (data | selectattr('role', 'defined')) + (data | subelements(['roles'], skip_missing=true)) }}"
> ...
> ```
> 
> What do you think?

I think you can go without as the `mandatory` filter on the input essentially does that job. If you don't specify `role` or `roles` you get the following output:

```
fatal: [localhost]: FAILED! => {"msg": "Mandatory variable 'role'  not defined."}
```
I think that will be fine to be honest.

2023-08-02 08:00 UTC, Tompage1994 commented on roles/roles/tasks/main.yml
> -    ansible_async_dir: '{{ controller_configuration_async_dir }}'
They are still there for the task that remains it's just hidden in the diff because nothing has changed. If you open up the full file you'll see it.

Unless I'm missing something...

2023-08-02 08:10 UTC, ivarmu commented on roles/roles/tasks/main.yml
> -    ansible_async_dir: '{{ controller_configuration_async_dir }}'
I'm sorry... you are right. I saw the tests were failling and thought in this at the first place:

https://github.com/redhat-cop/controller_configuration/actions/runs/5728794937/job/15524141848?pr=662

2023-08-02 08:19 UTC, ivarmu commented
> I think that will be fine to be honest.

Ok, just to be sure that my concern is clear... given the following example:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - data:
        - name: row1
          roles:
            - role1
            - role2
        - name: row2
          role: roleA
        - name: row3
  tasks:
    # - fail:
    #     msg: "The following input is incomplete: {{ current_bad_input }}"
    #   vars:
    #     bad_input: "{{ data | selectattr('role', 'undefined') | selectattr('roles', 'undefined') }}"
    #   loop: "{{ bad_input }}"
    #   loop_control:
    #     loop_var: current_bad_input

    - debug:
        msg:
          - "{{ item.1 if item.1 is defined else item.role }}"
      loop: "{{ (data | selectattr('role', 'defined')) + (data | subelements(['roles'], skip_missing=true)) }}"
...
```
This will skip the `data` -> `row3` item, as loop is selecting only the list items having defined either of `role` or `roles`, discarding any posible item without both of them, so the `mandatory` term will not have the opportunity to shine:

```console
ansible-playbook /tmp/test.yaml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'row2', 'role': 'roleA'}) => {
    "msg": [
        "roleA"
    ]
}
ok: [localhost] => (item=[{'name': 'row1', 'roles': ['role1', 'role2']}, 'role1']) => {
    "msg": [
        "role1"
    ]
}
ok: [localhost] => (item=[{'name': 'row1', 'roles': ['role1', 'role2']}, 'role2']) => {
    "msg": [
        "role2"
    ]
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

Do we want to let that kind of incomplete configuration entries in the input configuration as code?

2023-08-02 08:37 UTC, Tompage1994 commented
> 
That doesn't happen because instead of testing if `role` is defined, I've tested if `roles` is undefined, meaning if neither is set then it will be picked up and will spit out the error.

The only possible issue is when BOTH are defined, but in that case it will just use the `roles` option and `role` will be ignored

This:
tasks:
  - name: Include roles role at ../roles/roles
      ansible.builtin.include_role:
        name: ../roles/roles
      vars:
        controller_roles:
          - user: user1
            job_template: Demo Job Template
            roles:
              - read
              - execute
          - inventory: Demo Inventory
            user: user1
            role: read
          - job_template: Demo Job Template

Outputs this:
```
...
fatal: [localhost]: FAILED! => {
    "msg": "Mandatory variable 'role'  not defined."
}
```

2023-08-02 08:44 UTC, ivarmu approved these changes

2023-08-02 09:00 UTC, merged