Feature: improve checkmode outputs
redhat-cop/automate_tower_genie_collections pull request #715
Opened 2023-10-20 07:45 UTC by BobVanB

Checkmode has workable and readable output in console.

This code adds mainly these features:

* some labels to the output to make it readable.
* disable async with checkmode
* Checkmode wil fail at the end of the dispatch, to make it faster to fix multiple issues and not 1 by 1.

This is visible with a basic playbook command.

```shell
ansible-playbook --check ...
```

# Is there a relevant Issue open for this?

Not Available

# Other Relevant info, PRs, etc

Not Available

2023-10-30 18:36 UTC, djdanielsson commented
@sean-m-sullivan and/or @Tompage1994 thoughts? over all I didn't notice anything but want someone else to review as well

2023-11-01 03:47 UTC, sean-m-sullivan commented
Can you check this, there are now a ton of conflicts as other changes were done to labels, this looks good, but better for you to check then one of us make a mistake

2023-11-01 13:27 UTC, djdanielsson requested changes
please fix conflicts

2023-11-01 13:58 UTC, BobVanB commented
@djdanielsson i will do that. Will be tomorrow at best.

2023-11-02 11:51 UTC, sean-m-sullivan approved these changes

2023-11-02 12:00 UTC, sean-m-sullivan approved these changes
thanks for these changes, and thanks for addressing the rebase!

2023-11-02 12:00 UTC, merged