Cleanup task name
redhat-cop/automate_tower_genie_collections pull request #718
Opened 2023-10-25 17:12 UTC by dbk-rabel

This jinja2 template is never evaluated. The loop is inside the task. There is only one task and it was called literally: "Run infra.controller_configuration.{{ __role.role }}"

Very similar to #708

Although in this case I'm not sure if my proposed task name is the best.

Yours
  David

2023-10-26 09:15 UTC, dbk-rabel commented
I removed my linter cleanup commit. I think there is very many linter warnings right now. Might be possible to fix a lot of them with ansible-lint --write, but I think this is too much for this specific pull request.

2023-10-30 14:42 UTC, ivarmu commented
Hi @dbk-rabel, I prefer to let the current names to work properly, as proposed in the PR #716 for giving a solution to the issue #707.

So, if you feel confortable with this, we can close this issue as duplicated.

2023-10-30 14:43 UTC, ivarmu requested changes
Duplicate of issue #707 and PR #716

2023-10-30 14:47 UTC, dbk-rabel commented
> Hi @dbk-rabel, I prefer to let the current names to work properly, as proposed in the PR #716 for giving a solution to the issue #707.
> 
> So, if you feel confortable with this, we can close this issue as duplicated.

Yes, that's sounds good.  Thanks for putting in the effort!

2023-10-30 14:47 UTC, closed without merging