Provide 3 fixes for the diff plugin
redhat-cop/automate_tower_genie_collections pull request #726
Opened 2023-11-14 09:15 UTC by Rickmarges

# What does this PR do?

This PR contains 3 fixes for the diff plugin. I'll explain them one by one:

### 1. Usage access to instance_groups is removed:

When setting usage access to an instance_group (with `{"role": "use", "instance_groups": ["Dummy instance group"], "user": "test@example.com"}`) the diff plugin tries to remove it afterwards.
This is due to the API returning information in singular version, but as can been seen above, the role module requires the plural version.

```text
From API:
{
  "users": [
    "test@example.com"
  ],
  "teams": [],
  "name": "Use",
  "role": "Use",
  "type": "role",
  "resource_type": "instance_group",
  "instance_group": "Dummy instance group",
  "user": "test@example.com"
}

Diff plugin creates:
{
  "role": "use",
  "instance_group": "Dummy instance group",
  "user": "test@example.com",
  "state": "absent"
}

Should be:
{
  "role": "use",
  "instance_groups": [
    "Dummy instance group"
  ],
  "user": "test@example.com",
  "state": "absent"
}
```

This is fixed by converting the singular versions into plural.

### 2. When explicitly setting `state: present`, the plugin creates a present and absent object in some cases

In some cases (I've seen it happen with organizations, but might happen with more) when someone explicitly sets `state: present` in configuration (compare_list) the diff plugin returns 2 items, one absent and one present state.

```text
If compare list like this it works fine (no diff after first apply):
{
    "user": "test@example.com",
    "organizations": [
        "Dummy"
    ],
    "role": "admin"
},

If with explicit state present:
{
    "user": "test@example.com",
    "organizations": [
        "Dummy"
    ],
    "role": "admin",
    "state": "present"
},

Results in:
{
    "organizations": [
        "Dummy"
    ],
    "role": "admin",
    "state": "present",
    "user": "test@example.com"
},
{
    "organizations": [
        "Dummy"
    ],
    "role": "admin",
    "state": "absent",
    "user": "test@example.com"
},
```

This is fixed by changing the way the dicts are compared. A separate method is used where the `state` key is ignored.

### 3. Member rights to teams aren't removed

When a user should no longer be member of a certain team the configuration is removed. However, the diff plugin creates the wrong absent dict. Setting (or removing) membership access is done by using the `target_team` key, not `team`.

```text
Created by diff plugin:
{
    "role": "member",
    "state": "absent",
    "team": "dummy-team",
    "user": "test@example.com"
}

Should be:
{
    "role": "member",
    "state": "absent",
    "target_team": "dummy-team",
    "user": "test@example.com"
}
```
This is fixed by checking if the `team` key is present and the `role` is `member`. If both are true, update the dict to change `team` to `target_team`.

# How should this be tested?

Some items are automatically checked by the pipeline.
Otherwise tests can be performed based on the data provided in the code blocks above

# Is there a relevant Issue open for this?

# Other Relevant info, PRs, etc

2023-11-14 09:16 UTC, Rickmarges commented
Will rebase after #721 is merged (I've changed the same line as in that PR)

2023-11-15 07:49 UTC, ivarmu requested changes
Great catches! I think the `else` indentation seems to be wrong. Could you check this?

2023-11-15 07:49 UTC, ivarmu commented on plugins/lookup/controller_object_diff.py
> +                else:
Is this indentation correct?

2023-11-15 08:51 UTC, Rickmarges commented on plugins/lookup/controller_object_diff.py
> +                else:
Yes, the else is indented on the same level as the for loop on purpose.
Python allows you to set an else on a for loop to only execute if the loop did not encounter a break statement (https://book.pythontips.com/en/latest/for_-_else.html#else-clause)

2023-11-16 11:17 UTC, ivarmu commented on plugins/lookup/controller_object_diff.py
> +                else:
Ok, just to be sure it was the intention

2023-11-16 11:17 UTC, ivarmu approved these changes
LGTM

2023-11-19 16:08 UTC, sean-m-sullivan approved these changes

2023-11-19 16:08 UTC, sean-m-sullivan commented
Looks good to me, good additions, thanks!

2023-11-19 16:25 UTC, merged