Workflows
redhat-cop/automate_tower_genie_collections pull request #807
Opened 2024-04-04 14:48 UTC by djdanielsson

# What does this PR do?
updates some workflows dealing with issues

2024-04-05 10:03 UTC, Tompage1994 requested changes
Is this PR ready? 

It doesn't like the changes you've made to the PR template, could you fix please.

2024-04-05 13:03 UTC, djdanielsson commented
the PR template I just removed some white spaces so the comments would be right below the headings and make it easier to just write below it all, it isn't important just thought it might be a little better this way, if it isn't rendering correctly I can change it back

2024-04-18 14:18 UTC, djdanielsson commented
@Tompage1994  yes it is ready

2024-04-18 14:38 UTC, Tompage1994 approved these changes

2024-04-18 14:52 UTC, merged