feat: support of export single project/workflow/job
redhat-cop/automate_tower_genie_collections pull request #836
Opened 2024-05-27 14:03 UTC by przemkalit

# What does this PR do?
Add support for exporting a single project, job template, and workflow job template when the ID is provided.

Currently, filetree_create retrieves every project and other defined objects, which is not desirable in the following use cases scenario.

Use case scenario for project: 

1. The user creates a project in the QA AAP environment.
2. The user create many of job templates that use this project
3. The user wants to promote the project with job templates to the Production environment.
4. The user uses filetree_create to create a copy of the project with job templates and push the files to a remote repository.
5. The user uses filetree_read to import the object from the repository.

Use case scenario for workflow: 

1. The user creates a project in the QA AAP environment.
2. The user create many workflows that use this project
3. The user wants to promote the workflow to the Production environment.
4. The user uses filetree_create to create a copy of the workflow with related project and push the files to a remote repository.
5. The user uses filetree_read to import the object from the repository.

Use case scenario for job template: 

1. The user creates a project in the QA AAP environment.
2. The user create many job_templates that use this project
3. The user wants to promote the single job template to the Production environment.
4. The user uses filetree_create to create a copy of the job template with related project and push the files to a remote repository.
5. The user uses filetree_read to import the object from the repository.

# How should this be tested?
Manual
1) Provide the variables to the usage of the role:
```
- name: Get project
  hosts: all 
  roles:
    - role: infra.controller_configuration.filetree_create
      vars:
        organization_id: 1
        project_id: 4
  ```      
2) Execute the playbook and check if the only relevant data were exported.

# Is there a relevant Issue open for this?
N/A

# Other Relevant info, PRs, etc
N/A

2024-05-28 19:01 UTC, ivarmu requested changes
I'm adding comments for job templates that also apply to the other modified objects

2024-05-28 19:01 UTC, ivarmu commented on roles/filetree_create/README.md
> +| `job_id` | N/A | no | int | Specifiying the job template id to filter by. Exports the job template belonging to the specified organization. |
This can create confusion with `job_template_id ` and `job_id` (a job template run). Could this be renamed to `job_template_id`?

2024-05-28 19:01 UTC, ivarmu commented on roles/filetree_create/tasks/job_templates.yml
> +                                     (query_params | combine({'organization': organization_id, 'id': job_id})) if organization_id is defined and job_id is defined
If a `job_template_id` is specified, I think it'll belong to only one organization... so it have no sense specifying both inputs... am I wrong? In a similar way, I'm not sure right now if a project can be used from Job templates in different organizations...

2024-05-28 19:01 UTC, ivarmu commented
.

2024-05-29 06:09 UTC, przemkalit commented on roles/filetree_create/README.md
> +| `job_id` | N/A | no | int | Specifiying the job template id to filter by. Exports the job template belonging to the specified organization. |
Yes, you are right, I will rename it.

2024-05-29 06:17 UTC, przemkalit commented on roles/filetree_create/README.md
> +| `job_id` | N/A | no | int | Specifiying the job template id to filter by. Exports the job template belonging to the specified organization. |
I will rename the workflow_job_id to workflow_job_ template_id, as well.

2024-05-29 06:25 UTC, przemkalit commented on roles/filetree_create/tasks/job_templates.yml
> +                                     (query_params | combine({'organization': organization_id, 'id': job_id})) if organization_id is defined and job_id is defined
Okay, I think you are right because the database doesn't allow to have a the same id, I didn't think about it, thanks.

2024-05-29 07:44 UTC, ivarmu requested changes

2024-05-29 07:44 UTC, ivarmu commented on roles/filetree_create/tasks/job_templates.yml
> +                                     query_params,
I've been thinking about these lines and there's a problem with them... I tested to confirm my suspects... If `organization_id` is defined, neither `project_id` nor `job_template_id` will be used for the query... The same happens with `project_id`, that will avoid the usage of the `job_template_id`... Maybe the following approach should be better:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    query_params:
      param1: value1
    organization_id: 10
    project_id: 20
    job_template_id: 30
  tasks:
    - debug:
        msg:
          - "Current approach: {{ query_params | combine({'organization': organization_id}) if organization_id is defined
                else
                query_params | combine({'project_id': project_id}) if project_id is defined
                else
                query_params | combine({'id': job_template_id}) if job_template_id is defined
                else
                query_params
             }}"
          - "Proposed approach: {{ query_params | combine({'organization': organization_id} if organization_id is defined else {},
                                                          {'project_id': project_id} if project_id is defined else {},
                                                          {'job_template_id': job_template_id} if job_template_id is defined else {}
                                                         )
                                }}"
...
```

The output of the above is:

```console
PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "Current approach: {'param1': 'value1', 'organization': 10}",
        "Proposed approach: {'param1': 'value1', 'organization': 10, 'project_id': 20, 'job_template_id': 30}"
    ]
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

What do you think?

2024-05-29 07:55 UTC, przemkalit commented on roles/filetree_create/tasks/job_templates.yml
> +                                     query_params,
I must say, when I changed to this, I was aware of it. 

I thought about what you wrote, because as you wrote the organization_id is not mandatory to filter out the projects or job templates. Your proposal is changing it to the way that organization_id can be used with project_id etc. If it would be better for the project I could change to your suggestion.

2024-05-29 08:03 UTC, ivarmu commented on roles/filetree_create/tasks/job_templates.yml
> +                                     query_params,
Yeah, I agree that is changing my first review point of view... but I think it's more congruent like this, as if anyone provides the `job_template_id` alongside with `organization_id` and/or `project_id`, the expected, I think, is to have exported only the `job_template_id` that is associated with the already provided `project_id` from the `organization_id` organization... :-) sorry for being dizzy and thanks in advance for the changes :-)

2024-05-29 08:14 UTC, przemkalit commented on roles/filetree_create/tasks/job_templates.yml
> +                                     query_params,
No problem :-), I will add this modification, thanks for the feedback :-).

2024-05-29 09:25 UTC, ivarmu approved these changes
LGTM

2024-05-29 09:29 UTC, ivarmu requested changes
Please, fix the errors listed by the linter

2024-05-29 09:42 UTC, ivarmu requested changes

2024-05-29 09:42 UTC, ivarmu commented on roles/filetree_create/tasks/job_templates.yml
> +    job_templates_lookvar: "{{ query(controller_api_plugin, 'api/v2/job_templates/'
Missing a comma at the end of the line

2024-05-29 09:42 UTC, ivarmu commented on roles/filetree_create/tasks/projects.yml
> +                      }}"
Please, add the space that has been removed to maintain the alignment. Is not important, I know, sorry for my OCD :-)

2024-05-29 09:46 UTC, przemkalit commented on roles/filetree_create/tasks/job_templates.yml
> +    job_templates_lookvar: "{{ query(controller_api_plugin, 'api/v2/job_templates/'
Oh sorry, I think I am blind for commas :|.

2024-05-29 09:49 UTC, ivarmu approved these changes
LGTM

2024-05-29 10:51 UTC, ivarmu requested changes

2024-05-29 10:51 UTC, ivarmu commented on roles/filetree_create/tasks/workflow_job_templates.yml
> +                                              {'project_id': project_id} if project_id is defined else {},
The API is not accepting this parameter:

```console
TASK [infra.controller_configuration.filetree_create : Get current Workflow Job Templates from the API] **************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'awx.awx.controller_api'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to query the API: WorkflowJobTemplate has no field named 'project_id'. Failed to query the API: WorkflowJobTemplate has no field named 'project_id'"}
```

2024-05-29 11:01 UTC, przemkalit commented on roles/filetree_create/tasks/workflow_job_templates.yml
> +                                              {'project_id': project_id} if project_id is defined else {},
Ok, I've removed it. I was pretty sure that it was related, but I was mistaken.

2024-05-29 13:06 UTC, ivarmu approved these changes
LGTM

2024-05-31 14:25 UTC, silvinux requested changes
LGTM, but a changelog fragment file needs to be created: changelogs/fragments. Something similar to: 

---
Minor Changes:
  - filetree_create able to filter by project_id, workflow_job_template_id or job_template_id

https://github.com/redhat-cop/controller_configuration/blob/devel/changelogs/config.yaml

2024-06-05 07:31 UTC, przemkalit commented
Ok, I've added the missing changelog, anything more to add?

2024-06-12 13:21 UTC, silvinux approved these changes
LGTM

2024-06-13 08:24 UTC, merged