Update issue templates
redhat-cop/automate_tower_genie_collections pull request #852
Opened 2024-07-01 09:44 UTC by Tompage1994

2024-07-01 13:35 UTC, djdanielsson requested changes

2024-07-01 13:35 UTC, djdanielsson commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: Feature request
there is a link to feature requests to be on the forums currently that I think needs to get changed.

2024-07-01 13:35 UTC, djdanielsson commented on .github/ISSUE_TEMPLATE/bug_report.md
> +about: Create a bug report. Please test against the latest release before submitting
this should not say discussions but should talk about going to the forums for things that are not bug reports or feature requests.

2024-07-02 08:57 UTC, Tompage1994 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: Feature request
I think this changes it

2024-07-02 12:58 UTC, djdanielsson approved these changes
LGTM

2024-07-02 13:14 UTC, merged