Extra variables for workflow job templates and job templates
redhat-cop/automate_tower_genie_collections pull request #854
Opened 2024-07-01 13:10 UTC by przemkalit

# What does this PR do?
Hi, I want to introduce two variables that can later be used by other filetree_create tasks. The idea behind this is to allow the export of only job templates related to certain workflows and the projects associated with these job templates. I know that having a dictionary instead of a list of IDs or names may not be necessary, but it's good to have both options to avoid querying for the ID or name.

# How should this be tested?
```yaml
- name: Get the Workflow
  hosts: all 
  tasks:
    - name: Retrieve the workflow
      vars:
        workflow_job_template_id: 1
      ansible.builtin.include_role: infra.controller_configuration.filetree_create

    - name: Retrieve roles of job templates
      loop: "{{ workflow_node_jobs_dictvar | dict2items }}"
      vars:
        job_template_id: "{{ item.value }}"
      ansible.builtin.include_role: infra.controller_configuration.filetree_create
  
    - name: Retrieve the projects
      loop: "{{ projects_dictvar | dict2items }}"
      vars:
        project_id: "{{ item.value }}"
      ansible.builtin.include_role: infra.controller_configuration.filetree_create

```

# Is there a relevant Issue open for this?

N/A

# Other Relevant info, PRs, etc

This PR is related to #836.

2024-07-16 13:44 UTC, ivarmu approved these changes
LGTM

2024-07-16 15:27 UTC, adonisgarciac commented
I don't agree of defining variables in a role that will be used out of the role (they are being used in the playbook itself). Then, IMHO, that code should be part of the playbook and not part of the role.

I think the role should allow you export objects by certain IDs like was done in #836 but the role shouldn't define variables to be used out of it.

2024-07-16 15:50 UTC, djdanielsson requested changes
preventing merge until discussions have taken place to decide best approach

2024-07-18 11:51 UTC, przemkalit commented
> I don't agree of defining variables in a role that will be used out of the role (they are being used in the playbook itself). Then, IMHO, that code should be part of the playbook and not part of the role.
> 
> I think the role should allow you export objects by certain IDs like was done in #836 but the role shouldn't define variables to be used out of it.

Ok, I think I got your point, please check my newest changes.

2024-07-19 14:46 UTC, przemkalit commented
I've added a new change, if variable `export_related_objects` is defined and true, it should export related objects, if not it won't.

2024-07-26 13:56 UTC, djdanielsson approved these changes

2024-08-02 11:27 UTC, adonisgarciac commented on roles/filetree_create/defaults/main.yml
> +export_related_objects: true
I'd prefer to have false as default to keep previous behavior as default.

2024-08-02 11:28 UTC, adonisgarciac commented on roles/filetree_create/tasks/job_templates.yml
> +- name: "Export project related to job_template"
If I'm not wrong, this is not going to work. This is taking only first JT from job_templates_lookvar which is a list. Therefore, only the project of first JT exported will be exported as well.

2024-08-05 14:02 UTC, djdanielsson commented
@adonisgarciac  are you good with this now?

2024-08-05 14:50 UTC, adonisgarciac commented
> @adonisgarciac are you good with this now?

I don't think so. I wrote 2 comments that were not reviewed by @przemkalit. IMO, with those changes, we're getting only one element of a list so if I'm not wrong, it does not make sense.

@przemkalit it would be great if you could look over my previous comments

2024-08-05 14:50 UTC, adonisgarciac requested changes

2024-08-05 14:50 UTC, adonisgarciac commented on roles/filetree_create/tasks/workflow_job_templates.yml
> +- name: "Block for matching job templates ids with names for given workflow"
If I'm not wrong, this is not going to work. This is taking only first WFJT from workflow_job_templates_lookvar which is a list. Therefore, only the nodes of first WFJT exported will be exported as well.

2024-08-05 14:50 UTC, adonisgarciac commented on roles/filetree_create/tasks/job_templates.yml
> +- name: "Export project related to job_template"
If I'm not wrong, this is not going to work. This is taking only first JT from job_templates_lookvar which is a list. Therefore, only the project of first JT exported will be exported as well.

2024-08-05 14:50 UTC, adonisgarciac commented on roles/filetree_create/defaults/main.yml
> +export_related_objects: true
I'd prefer to have false as default to keep previous default behavior

2024-08-05 14:58 UTC, przemkalit commented
> > @adonisgarciac are you good with this now?
> 
> I don't think so. I wrote 2 comments that were not reviewed by @przemkalit. IMO, with those changes, we're getting only one element of a list so if I'm not wrong, it does not make sense.
> 
> @przemkalit it would be great if you could look over my previous comments
@adonisgarciac 
Just a quick note from my side: I saw the comments in the email notifications, but I couldn't find them in the PR conversation. I thought they might have been deleted. I'll check the suggestions by tomorrow.

2024-08-06 06:11 UTC, przemkalit commented on roles/filetree_create/defaults/main.yml
> +export_related_objects: true
Resolved.

2024-08-06 06:35 UTC, przemkalit commented on roles/filetree_create/tasks/workflow_job_templates.yml
> +- name: "Block for matching job templates ids with names for given workflow"
I get your point, but behind this is idea that task is exporting single WFJT with related JTs, that's why I am taking first element from the list. I could change it but I believe it would complicated because I would need check if someone is exporting only WFs and not the JTs.

2024-08-06 06:37 UTC, przemkalit commented on roles/filetree_create/tasks/job_templates.yml
> +- name: "Export project related to job_template"
The same goes here, idea the same, export JT with project.  And that's why there is when statement which check if the id for JT is provided.

2024-08-07 06:49 UTC, adonisgarciac approved these changes

2024-08-07 06:49 UTC, adonisgarciac commented on roles/filetree_create/README.md
> +| `export_related_objects` | False | no | bool | Whether to export releated objects to workflows and job templates. |
Indicate that this will only apply if you're exporting a single JT or a single WFJT. For instance: 

Whether to export related objects to workflows or job templates when a single JT or a single WFJT are being exported

2024-08-07 06:49 UTC, adonisgarciac commented on roles/filetree_create/README.md
> +| `export_related_objects` | False | no | bool | Whether to export releated objects to workflows and job templates. |
solved!

2024-08-07 13:44 UTC, merged