Idea of managing errors while creating the objects in controller
redhat-cop/automate_tower_genie_collections pull request #862
Opened 2024-07-10 11:44 UTC by przemkalit

# What does this PR do?
This PR proposes a method to manage errors while creating objects in the controller.

Background: I was testing the collection in our environment and encountered an annoying issue. While restoring objects from files created with filetree_create, the dispatch role stopped every time it encountered a problem, such as when an object was missing something (e.g., a playbook could not be found in the project). 

I came up with a block and rescue directive for the async task. The rescue block extracts errors from the result file and puts them into a list of dicts, which is then set as an artifact.

If you like this idea, I will introduce it to every object in the collection. However, if you have a different approach to this problem, I am open to suggestions.

# How should this be tested?
1) Create job_templates which playbook does not exist in the project in target controller.
2) Export with filetree_create.
2) Execute playbook:
```yaml
- name: Restore objects
   hosts: all 
   tasks:
     - name: Include vars from path directory
       ansible.builtin.include_vars:
         dir: '/path'
         extensions:
           - "yml"
           - "yaml"
      
     - ansible.builtin.include_role: infra.controller_configuration.filetree_read
      
     - ansible.builtin.include_role: infra.controller_configuration.dispatch
```
# Is there a relevant Issue open for this?

N/A

# Other Relevant info, PRs, etc
N/A

2024-07-10 12:47 UTC, djdanielsson commented
It's an interesting idea, we will have to do quite a bit of testing to ensure this doesn't break anything. When I have some time I will try it out and give more detailed feedback

2024-07-12 13:13 UTC, djdanielsson commented on roles/.DS_Store
delete this file please

2024-07-12 13:16 UTC, przemkalit commented on roles/.DS_Store
oh, sorry I try to watch over this file created by VSCode, removed.

2024-07-12 13:26 UTC, Tompage1994 requested changes
Overall I think this is good and may be useful. I don't think it will slow down execution and I believe it to be scalable.

I haven't tested this on a live system.

It would be good though if you could have a go at adding into our [CI testing](https://github.com/redhat-cop/controller_configuration/blob/devel/tests/configure_controller.yml). Get a JT which will fail and assert that the output is correct

2024-07-12 13:26 UTC, Tompage1994 commented on roles/job_templates/tasks/async.yml
> +        name: error_data
Can you rename the internal vars here to be prepended with `__` to fit in with existing coding practices.

e.g. `name: __error_data`
e.g. `__templates_error_list `

2024-07-12 13:26 UTC, Tompage1994 commented on roles/job_templates/tasks/async.yml
We are missing the `...` at the end of the file. Please ensure that the linting is passing before we can merge this

2024-07-12 13:52 UTC, przemkalit commented on roles/job_templates/tasks/async.yml
Ok I will work on the JT.

2024-07-12 13:52 UTC, przemkalit commented
> Overall I think this is good and may be useful. I don't think it will slow down execution and I believe it to be scalable.
> 
> I haven't tested this on a live system.
> 
> It would be good though if you could have a go at adding into our [CI testing](https://github.com/redhat-cop/controller_configuration/blob/devel/tests/configure_controller.yml). Get a JT which will fail and assert that the output is correct

Ok I will work on JT.

2024-07-15 09:52 UTC, przemkalit commented
Please let me know if the test provided by me is sufficient or should I make some changes.

2024-07-15 10:03 UTC, Tompage1994 commented
> Please let me know if the test provided by me is sufficient or should I make some changes.

The testing you've done looks good but is unfortunately in the wrong place. Could you add it to the following section:

https://github.com/redhat-cop/controller_configuration/blob/devel/tests/configure_controller.yml

2024-07-15 10:37 UTC, Tompage1994 approved these changes
Thanks, that looked better.

I've just done a quick refactor of the test and pushed it to this PR to simplify it a little bit. If you're happy with that then I'm happy to merge this

2024-07-15 10:44 UTC, przemkalit commented
Thanks for the refactor, so as you approved this kind of error handling, could I add this change to the workflows, or should I added with a new PR?

2024-07-15 11:28 UTC, Tompage1994 commented
@przemkalit Ok, I've made another change to the testing because we don't set the variables as we are setting stat rather than vars.

There is a bigger conversation to be had here about how we want to handle these errors, whether we want to fail the playbook by default (I think we may want to add in a variable here to set to fail on error. As it is this will continue on error)

In terms of creating the same on other roles, I would hold off for now. It may all go through this PR or could be separate but we need to decide how we want this to go for now. This will now sit here for a bit whilst we internally discuss and decide on direction.

Thanks for the contribution

2024-07-26 13:29 UTC, przemkalit commented
Hi, I've added small change which is related to existence of variables in eg. `extra_vars`.

2024-07-26 13:36 UTC, djdanielsson commented on roles/job_templates/tasks/main.yml
> +  ansible.builtin.include_tasks: "{{ role_path }}/tasks/async.yml"
do you really have to give it the path like this instead of `ansible.builtin.include_tasks: async.yml`

2024-07-26 13:44 UTC, przemkalit commented on roles/job_templates/tasks/main.yml
> +  ansible.builtin.include_tasks: "{{ role_path }}/tasks/async.yml"
I've changed it because the CI testing was failing. The playbook tried to include the async file from the test playbook path instead of the role path.

2024-08-05 21:29 UTC, djdanielsson commented
update the branch and I will merge it

2024-08-06 13:17 UTC, djdanielsson commented
@Tompage1994 ready to merge it?

2024-08-22 19:36 UTC, djdanielsson commented
@Tompage1994 reminder, are you good with this now?

2024-08-22 19:46 UTC, Tompage1994 commented
> @Tompage1994 reminder, are you good with this now?

Yes I'm good with it. We will want to look into replicating this across all the roles

2024-08-22 19:52 UTC, merged