fix default value for *_credentials_secure_logging in README
redhat-cop/automate_tower_genie_collections pull request #992
Opened 2024-12-03 11:37 UTC by akira6592

# What does this PR do?

fix default value for `*_credentials_secure_logging` in README.

# How should this be tested?

N/A (Document only)

# Is there a relevant Issue open for this?

resolves #990 

# Other Relevant info, PRs, etc

N/A (Document only)

2024-12-03 14:18 UTC, djdanielsson requested changes

2024-12-03 14:18 UTC, djdanielsson commented on roles/controller_credentials/README.md
> +|`controller_configuration_credentials_enforce_defaults`|`true`|no|Whether or not to enforce default option values on only the applications role|
I believe you meant, controller_configuration_credentials_secure_logging not controller_configuration_credentials_enforce_defaults

2024-12-04 00:02 UTC, akira6592 commented on roles/controller_credentials/README.md
> +|`controller_configuration_credentials_enforce_defaults`|`true`|no|Whether or not to enforce default option values on only the applications role|
@djdanielsson Thank you for review. I fixed it.

2024-12-04 13:41 UTC, djdanielsson approved these changes
LGTM

2024-12-04 13:43 UTC, merged

2024-12-04 23:49 UTC, akira6592 commented
Thank you for merging!